-- Pixel avatars (art_version 3): 8-bit avatars in the style of 8 Bit Evil
-- Returns, drawn in pixel-avatar/. They replace the v2 avatars outright.
--
-- Rollout, in order:
--   1. this migration (retires every v2 item, clears outfits, refunds v2 shop
--      purchases, points the starter pack at art_version 3)
--   2. server/db/avatar_catalog.sql (generated by `npm run art:avatar`), which
--      upserts the pixel items; re-run it whenever items change
--   3. deploy the server and site together (the API only serves art_version 3)
-- Everyone gets the pixel starter pack and a default look on their next
-- avatar load; the site then rolls them a random kid from the free items and
-- saves it (build_chosen, sent as lookChosen, marks that it has happened).

-- Retire the v2 items: they stop being granted, sold or listed.
UPDATE public.avatar_items
SET release_status = 'retired',
    is_starter = FALSE,
    is_default = FALSE,
    is_tradeable = FALSE,
    is_sellable = FALSE
WHERE art_version = 2;

-- Take v2 items off the market.
UPDATE public.marketplace_listings ml
SET status = 'canceled', canceled_at = now(), updated_at = now()
FROM public.avatar_items ai
WHERE ai.id = ml.item_id
  AND ai.art_version = 2
  AND ml.status = 'active';

-- Refund what people paid in the shop for v2 items they still hold.
WITH refunds AS (
    SELECT uii.user_id, uii.id AS item_instance_id, ai.item_key, -ct.amount AS amount
    FROM public.user_item_instances uii
    JOIN public.avatar_items ai ON ai.id = uii.item_id
    JOIN public.currency_transactions ct
      ON ct.user_id = uii.user_id
     AND ct.source_type = 'shop_purchase'
     AND ct.source_id = uii.id::TEXT
     AND ct.amount < 0
    WHERE ai.art_version = 2
      AND uii.status IN ('owned', 'listed')
),
totals AS (
    SELECT user_id, sum(amount) AS amount, jsonb_agg(item_key) AS item_keys
    FROM refunds
    GROUP BY user_id
),
paid AS (
    UPDATE public.user_wallets w
    SET coin_balance = w.coin_balance + t.amount, updated_at = now()
    FROM totals t
    WHERE w.user_id = t.user_id
    RETURNING w.user_id, w.coin_balance, t.amount, t.item_keys
)
INSERT INTO public.currency_transactions (user_id, amount, balance_after, transaction_type, source_type, metadata)
SELECT user_id, amount, coin_balance, 'refund', 'avatar_v2_retired', jsonb_build_object('itemKeys', item_keys)
FROM paid;

-- Nobody wears or holds v2 items any more.
DELETE FROM public.user_outfit_items uoi
USING public.avatar_items ai
WHERE ai.id = uoi.item_id
  AND ai.art_version <> 3;

UPDATE public.user_item_instances uii
SET status = 'consumed', updated_at = now()
FROM public.avatar_items ai
WHERE ai.id = uii.item_id
  AND ai.art_version = 2
  AND uii.status IN ('owned', 'listed', 'locked');

-- Fresh profiles: the pixel defaults, and a random look still to roll.
ALTER TABLE public.user_avatar_profile
    ALTER COLUMN skin SET DEFAULT 'peach',
    ALTER COLUMN hair SET DEFAULT 'sandy',
    ALTER COLUMN eyes SET DEFAULT 'ink_eye';

UPDATE public.user_avatar_profile
SET skin = 'peach', hair = 'sandy', eyes = 'ink_eye', build_chosen = FALSE, updated_at = now();

-- Gives a user everything their avatar needs. Safe to call on every load:
-- new starter items reach existing users, and an empty outfit is refilled
-- with the defaults.
CREATE OR REPLACE FUNCTION public.seed_user_avatar_defaults(target_user_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    -- Two loads at once must not both grant the starter pack.
    PERFORM pg_advisory_xact_lock(hashtext('seed_user_avatar_defaults:' || target_user_id::TEXT));
    PERFORM public.ensure_user_wallet(target_user_id);

    INSERT INTO public.user_item_instances (user_id, item_id, status, source_type)
    SELECT target_user_id, ai.id, 'owned', 'starter'
    FROM public.avatar_items ai
    WHERE ai.art_version = 3
      AND ai.is_starter = TRUE
      AND ai.release_status = 'released'
      AND NOT EXISTS (
          SELECT 1
          FROM public.user_item_instances uii
          WHERE uii.user_id = target_user_id
            AND uii.item_id = ai.id
      );

    INSERT INTO public.user_avatar_profile (user_id)
    VALUES (target_user_id)
    ON CONFLICT (user_id) DO NOTHING;

    IF NOT EXISTS (SELECT 1 FROM public.user_outfit_items WHERE user_id = target_user_id) THEN
        INSERT INTO public.user_outfit_items (user_id, item_instance_id, item_id)
        SELECT DISTINCT ON (ai.id) target_user_id, uii.id, ai.id
        FROM public.avatar_items ai
        JOIN public.user_item_instances uii
          ON uii.item_id = ai.id
         AND uii.user_id = target_user_id
         AND uii.status = 'owned'
        WHERE ai.art_version = 3
          AND ai.is_default = TRUE
        ORDER BY ai.id, uii.id;
    END IF;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.seed_user_avatar_defaults(uuid) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.seed_user_avatar_defaults(uuid) TO service_role;
