-- The shop's fifth round: 21 more avatar items (a dog and a tabby cat; flies and stink lines, as
-- auras; and the rest of five outfits: the mummy's head, leg and foot wraps; the pumpkin's bloomers
-- and leaf slippers; the witch's bodice, skirt and buckle shoes; the devil's suit, leggings, hooves,
-- tail and pitchfork; the angel's robe, its skirt, sandals and a harp), added if missing. Rows from
-- avatar_catalog.sql (made by npm run art:avatar). Run by the server at start; harmless to run again.

INSERT INTO public.avatar_items (
    item_key, name, slot, equip_group, layer_order, asset_path,
    is_default, is_starter, is_tradeable, is_sellable, rarity, base_price, release_status,
    metadata, art_version, category, parts, dyes, hides, occupies, stack_order
)
VALUES
('angel_robe', 'Angel Robe', 'torso', 'torso', 0, '/avatar-px/items/angel_robe/icon.png?v=eda8cad3f2', false, false, true, true, 'uncommon', 130, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/angel_robe/0-torso.png?v=5549d892d1","fits":["body_kid"]}]'::jsonb, '{"dye1":"cloud"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('angel_robe_skirt', 'Angel Robe Skirt', 'legs', 'legs', 0, '/avatar-px/items/angel_robe_skirt/icon.png?v=8cceedd58b', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/angel_robe_skirt/0-legs.png?v=add25636d3","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":12,"y":41,"w":7,"h":4,"frames":1,"src":"/avatar-px/items/angel_robe_skirt/1-legs.png?v=9ddd59b4bc","fits":["body_kid"]}]'::jsonb, '{"dye1":"cloud"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('buckle_shoes', 'Buckle Shoes', 'feet', 'feet', 0, '/avatar-px/items/buckle_shoes/icon.png?v=1793fc53e3', false, false, true, true, 'uncommon', 80, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":44,"w":7,"h":3,"frames":1,"src":"/avatar-px/items/buckle_shoes/0-feet.png?v=4d8c0f71da","fits":["body_kid"]}]'::jsonb, '{"dye1":"coal"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('cloven_hooves', 'Cloven Hooves', 'feet', 'feet', 0, '/avatar-px/items/cloven_hooves/icon.png?v=0df94e888c', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":44,"w":7,"h":3,"frames":1,"src":"/avatar-px/items/cloven_hooves/0-feet.png?v=d9c0cb6fd2","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('devil_leggings', 'Devil Leggings', 'legs', 'legs', 0, '/avatar-px/items/devil_leggings/icon.png?v=6dcad027c5', false, false, true, true, 'common', 70, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/devil_leggings/0-legs.png?v=85190ce4df","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":13,"y":41,"w":5,"h":4,"frames":1,"src":"/avatar-px/items/devil_leggings/1-legs.png?v=0b8bb6af4c","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('devil_suit', 'Devil Suit', 'torso', 'torso', 0, '/avatar-px/items/devil_suit/icon.png?v=1ed0dc819e', false, false, true, true, 'uncommon', 120, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/devil_suit/0-torso.png?v=972380a932","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('devil_tail', 'Devil Tail', 'back', 'back', 0, '/avatar-px/items/devil_tail/icon.png?v=a4054062fe', false, false, true, true, 'uncommon', 100, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'back', '[{"slot":"back","anchor":"body","x":18,"y":35,"w":5,"h":7,"frames":1,"src":"/avatar-px/items/devil_tail/0-back.png?v=ff81edf7db","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('dog', 'Dog', 'companion', 'companion', 0, '/avatar-px/items/dog/icon.png?v=5a656904cb', false, false, true, true, 'rare', 260, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":20,"y":37,"w":10,"h":10,"frames":6,"src":"/avatar-px/items/dog/0-companion.png?v=c74996f770"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('flies', 'Flies', 'aura', 'aura', 0, '/avatar-px/items/flies/icon.png?v=b4697eff51', false, false, true, true, 'uncommon', 150, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"front_fx","anchor":"free","x":1,"y":15,"w":30,"h":30,"frames":6,"src":"/avatar-px/items/flies/0-front_fx.png?v=9fb59d817d"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('golden_sandals', 'Golden Sandals', 'feet', 'feet', 0, '/avatar-px/items/golden_sandals/icon.png?v=969924777c', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":44,"w":7,"h":3,"frames":1,"src":"/avatar-px/items/golden_sandals/0-feet.png?v=7a5981d2dc","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('leaf_slippers', 'Leaf Slippers', 'feet', 'feet', 0, '/avatar-px/items/leaf_slippers/icon.png?v=2eb6ceb65e', false, false, true, true, 'uncommon', 80, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":11,"y":44,"w":9,"h":3,"frames":1,"src":"/avatar-px/items/leaf_slippers/0-feet.png?v=da308f5027","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('little_harp', 'Little Harp', 'held', 'held', 0, '/avatar-px/items/little_harp/icon.png?v=8c87bec465', false, false, true, true, 'rare', 200, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":5,"y":31,"w":5,"h":6,"frames":1,"src":"/avatar-px/items/little_harp/0-held.png?v=3e653efe83","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('mummy_foot_wraps', 'Mummy Foot Wraps', 'feet', 'feet', 0, '/avatar-px/items/mummy_foot_wraps/icon.png?v=68514abc4d', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":44,"w":7,"h":3,"frames":1,"src":"/avatar-px/items/mummy_foot_wraps/0-feet.png?v=ef8eeb2e86","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('mummy_head_wraps', 'Mummy Head Wraps', 'face_acc', 'face_acc', 0, '/avatar-px/items/mummy_head_wraps/icon.png?v=ad9480616b', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'face_acc', '[{"slot":"face_acc","anchor":"head","x":11,"y":26,"w":9,"h":8,"frames":1,"src":"/avatar-px/items/mummy_head_wraps/0-face_acc.png?v=c9799b101e","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('mummy_leg_wraps', 'Mummy Leg Wraps', 'legs', 'legs', 0, '/avatar-px/items/mummy_leg_wraps/icon.png?v=36dd9a7915', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/mummy_leg_wraps/0-legs.png?v=aaadd20091","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":13,"y":41,"w":5,"h":4,"frames":1,"src":"/avatar-px/items/mummy_leg_wraps/1-legs.png?v=80bb2720f8","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('pitchfork', 'Pitchfork', 'held', 'held', 0, '/avatar-px/items/pitchfork/icon.png?v=5eecf26bea', false, false, true, true, 'rare', 220, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":18,"w":5,"h":25,"frames":1,"src":"/avatar-px/items/pitchfork/0-held.png?v=f5c5da3a5b","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('pumpkin_bloomers', 'Pumpkin Bloomers', 'legs', 'legs', 0, '/avatar-px/items/pumpkin_bloomers/icon.png?v=66babf56aa', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/pumpkin_bloomers/0-legs.png?v=5e2e3d1c42","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":12,"y":41,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/pumpkin_bloomers/1-legs.png?v=c930f256fd","fits":["body_kid"]}]'::jsonb, '{"dye1":"orange"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('stink_lines', 'Stink Lines', 'aura', 'aura', 0, '/avatar-px/items/stink_lines/icon.png?v=133438f5f4', false, false, true, true, 'uncommon', 170, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"front_fx","anchor":"free","x":1,"y":15,"w":26,"h":30,"frames":6,"src":"/avatar-px/items/stink_lines/0-front_fx.png?v=a71c657f0d"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('tabby_cat', 'Tabby Cat', 'companion', 'companion', 0, '/avatar-px/items/tabby_cat/icon.png?v=7f834189c8', false, false, true, true, 'rare', 260, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":20,"y":37,"w":9,"h":10,"frames":6,"src":"/avatar-px/items/tabby_cat/0-companion.png?v=f8e07f82fe"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('witch_dress', 'Witch''s Bodice', 'torso', 'torso', 0, '/avatar-px/items/witch_dress/icon.png?v=f3c076f339', false, false, true, true, 'uncommon', 120, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/witch_dress/0-torso.png?v=3f5a70dd70","fits":["body_kid"]}]'::jsonb, '{"dye1":"plum"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('witch_skirt', 'Witch''s Skirt', 'legs', 'legs', 0, '/avatar-px/items/witch_skirt/icon.png?v=ed84e59797', false, false, true, true, 'uncommon', 100, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/witch_skirt/0-legs.png?v=85190ce4df","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":11,"y":41,"w":9,"h":3,"frames":1,"src":"/avatar-px/items/witch_skirt/1-legs.png?v=2c9ca35fc3","fits":["body_kid"]}]'::jsonb, '{"dye1":"plum"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0)
ON CONFLICT (item_key) DO NOTHING;
