-- Avatar v2: layered, dyeable items drawn in avatar-art/, two body builds
-- (f and m), and equip categories with per-category limits.
--
-- Rollout, in order:
--   1. this migration (schema, retires the old single-sprite items)
--   2. server/db/avatar_catalog.sql (generated by `npm run art:avatar`), which
--      upserts the v2 items; re-run it whenever items change
-- Users move over lazily: the first time seed_user_avatar_defaults runs for
-- them (on sign-up, or their next avatar load) they get the v2 starter pack,
-- the default outfit and, if they had customized their old avatar, the closest
-- v2 look. Old rows in user_avatar and old item instances are left in place.

ALTER TABLE public.avatar_items
    ADD COLUMN IF NOT EXISTS art_version SMALLINT NOT NULL DEFAULT 1,
    ADD COLUMN IF NOT EXISTS category TEXT,
    ADD COLUMN IF NOT EXISTS parts JSONB NOT NULL DEFAULT '[]'::jsonb,
    ADD COLUMN IF NOT EXISTS dyes JSONB NOT NULL DEFAULT '{}'::jsonb,
    ADD COLUMN IF NOT EXISTS hides TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS occupies TEXT[] NOT NULL DEFAULT '{}',
    ADD COLUMN IF NOT EXISTS stack_order INTEGER NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_avatar_items_art_category
    ON public.avatar_items (art_version, category);

-- Retire the old items: they stop being granted, sold or listed.
UPDATE public.avatar_items
SET release_status = 'retired',
    is_starter = FALSE,
    is_default = FALSE,
    is_tradeable = FALSE,
    is_sellable = FALSE
WHERE art_version = 1;

-- Hand back any old items still up for sale.
WITH canceled AS (
    UPDATE public.marketplace_listings ml
    SET status = 'canceled', canceled_at = now(), updated_at = now()
    FROM public.avatar_items ai
    WHERE ai.id = ml.item_id
      AND ai.art_version = 1
      AND ml.status = 'active'
    RETURNING ml.item_instance_id
)
UPDATE public.user_item_instances uii
SET status = 'owned', updated_at = now()
FROM canceled
WHERE uii.id = canceled.item_instance_id
  AND uii.status = 'listed';

-- Build, skin and colours for each user's avatar.
CREATE TABLE IF NOT EXISTS public.user_avatar_profile (
    user_id UUID PRIMARY KEY REFERENCES public.users (id) ON DELETE CASCADE,
    build TEXT NOT NULL DEFAULT 'f',
    build_chosen BOOLEAN NOT NULL DEFAULT FALSE,
    skin TEXT NOT NULL DEFAULT 'skin',
    hair TEXT NOT NULL DEFAULT 'hair',
    eyes TEXT NOT NULL DEFAULT 'eyes',
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    CONSTRAINT user_avatar_profile_build_check CHECK (build IN ('f', 'm'))
);

-- What each user is wearing, with the dyes they picked per item.
CREATE TABLE IF NOT EXISTS public.user_outfit_items (
    user_id UUID NOT NULL REFERENCES public.users (id) ON DELETE CASCADE,
    item_instance_id BIGINT NOT NULL REFERENCES public.user_item_instances (id) ON DELETE CASCADE,
    item_id INTEGER NOT NULL REFERENCES public.avatar_items (id),
    dyes JSONB NOT NULL DEFAULT '{}'::jsonb,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    PRIMARY KEY (user_id, item_instance_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS user_outfit_items_instance_key
    ON public.user_outfit_items (item_instance_id);

-- How an old look carries over: a skin or hair colour to use, a v2 item to
-- wear in its place, and a v2 item to give in exchange for owning it (for
-- items people paid for).
CREATE TABLE IF NOT EXISTS public.avatar_legacy_map (
    legacy_key TEXT PRIMARY KEY,
    skin TEXT,
    hair TEXT,
    equip_key TEXT,
    exchange_key TEXT
);

INSERT INTO public.avatar_legacy_map (legacy_key, skin, hair, equip_key, exchange_key)
VALUES
    ('pale_body', 'skin_pale', NULL, NULL, NULL),
    ('green_zombie_body', 'skin_zombie', NULL, NULL, NULL),
    ('white_witch_hair', NULL, 'bone', NULL, NULL),
    ('pumpkin_orange_hair', NULL, 'pumpkin', NULL, NULL),
    ('black_shaggy_hair', NULL, 'night', NULL, NULL),
    ('fang_face', NULL, NULL, 'mouth_fang', NULL),
    ('sleepy_face', NULL, NULL, 'eyes_sleepless', NULL),
    ('bat_wings', NULL, NULL, 'tattered_bat_wings', NULL),
    ('skull_pin', NULL, NULL, 'charm_choker', NULL),
    ('scareathon_hoodie', NULL, NULL, 'stitchwork_sweater', NULL),
    ('sneakers', NULL, NULL, 'grave_creepers', NULL),
    ('pumpkin_hat', NULL, NULL, 'witch_hat', NULL),
    ('pumkin_hat', NULL, NULL, 'witch_hat', 'witch_hat')
ON CONFLICT (legacy_key) DO UPDATE SET
    skin = EXCLUDED.skin,
    hair = EXCLUDED.hair,
    equip_key = EXCLUDED.equip_key,
    exchange_key = EXCLUDED.exchange_key;

-- Server-only tables, like the rest of the avatar data.
ALTER TABLE public.user_avatar_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.user_outfit_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.avatar_legacy_map ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.user_avatar_profile FROM anon, authenticated;
REVOKE ALL ON public.user_outfit_items FROM anon, authenticated;
REVOKE ALL ON public.avatar_legacy_map FROM anon, authenticated;

-- Moves one user's old look over. Called once, when their v2 profile is created.
CREATE OR REPLACE FUNCTION public.carry_over_legacy_avatar(target_user_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    mapped RECORD;
    new_item public.avatar_items;
    instance_id BIGINT;
BEGIN
    -- Skin and hair colours from the old body and hair they wore.
    UPDATE public.user_avatar_profile profile
    SET skin = COALESCE(worn.skin, profile.skin),
        hair = COALESCE(worn.hair, profile.hair),
        updated_at = now()
    FROM (
        SELECT max(lm.skin) AS skin, max(lm.hair) AS hair
        FROM public.user_avatar ua
        JOIN public.avatar_items ai ON ai.id = ua.item_id
        JOIN public.avatar_legacy_map lm ON lm.legacy_key = ai.item_key
        WHERE ua.user_id = target_user_id
    ) worn
    WHERE profile.user_id = target_user_id;

    -- Items they paid for become their v2 counterpart.
    FOR mapped IN
        SELECT uii.id AS legacy_instance_id, ai.item_key AS legacy_key, lm.exchange_key
        FROM public.user_item_instances uii
        JOIN public.avatar_items ai ON ai.id = uii.item_id
        JOIN public.avatar_legacy_map lm ON lm.legacy_key = ai.item_key
        WHERE uii.user_id = target_user_id
          AND uii.status = 'owned'
          AND ai.art_version = 1
          AND lm.exchange_key IS NOT NULL
    LOOP
        SELECT * INTO new_item
        FROM public.avatar_items
        WHERE item_key = mapped.exchange_key AND art_version = 2;
        CONTINUE WHEN NOT FOUND;

        PERFORM public.grant_item_instance(
            target_user_id, new_item.id, 'legacy_exchange', mapped.legacy_instance_id::TEXT,
            jsonb_build_object('legacyKey', mapped.legacy_key)
        );
        UPDATE public.user_item_instances
        SET status = 'consumed', updated_at = now()
        WHERE id = mapped.legacy_instance_id;
    END LOOP;

    -- Old items they were wearing: wear the v2 counterpart instead, granting it if needed.
    FOR mapped IN
        SELECT DISTINCT ON (lm.equip_key) lm.equip_key, ai.item_key AS legacy_key, ua.item_instance_id AS legacy_instance_id
        FROM public.user_avatar ua
        JOIN public.avatar_items ai ON ai.id = ua.item_id
        JOIN public.avatar_legacy_map lm ON lm.legacy_key = ai.item_key
        WHERE ua.user_id = target_user_id
          AND lm.equip_key IS NOT NULL
        ORDER BY lm.equip_key
    LOOP
        SELECT * INTO new_item
        FROM public.avatar_items
        WHERE item_key = mapped.equip_key AND art_version = 2;
        CONTINUE WHEN NOT FOUND;

        SELECT id INTO instance_id
        FROM public.user_item_instances
        WHERE user_id = target_user_id AND item_id = new_item.id AND status = 'owned'
        ORDER BY id
        LIMIT 1;

        IF instance_id IS NULL THEN
            instance_id := public.grant_item_instance(
                target_user_id, new_item.id, 'legacy_carryover', mapped.legacy_instance_id::TEXT,
                jsonb_build_object('legacyKey', mapped.legacy_key)
            );
        END IF;

        DELETE FROM public.user_outfit_items uoi
        USING public.avatar_items ai
        WHERE uoi.user_id = target_user_id
          AND ai.id = uoi.item_id
          AND ai.category = new_item.category;

        INSERT INTO public.user_outfit_items (user_id, item_instance_id, item_id)
        VALUES (target_user_id, instance_id, new_item.id)
        ON CONFLICT DO NOTHING;
    END LOOP;
END;
$$;

-- Gives a user everything their avatar needs. Safe to call on every load:
-- new starter items reach existing users, and an empty outfit is refilled
-- with the defaults.
CREATE OR REPLACE FUNCTION public.seed_user_avatar_defaults(target_user_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
    created_profiles INTEGER;
BEGIN
    -- Two loads at once must not both grant the starter pack.
    PERFORM pg_advisory_xact_lock(hashtext('seed_user_avatar_defaults:' || target_user_id::TEXT));
    PERFORM public.ensure_user_wallet(target_user_id);

    INSERT INTO public.user_item_instances (user_id, item_id, status, source_type)
    SELECT target_user_id, ai.id, 'owned', 'starter'
    FROM public.avatar_items ai
    WHERE ai.art_version = 2
      AND ai.is_starter = TRUE
      AND ai.release_status = 'released'
      AND NOT EXISTS (
          SELECT 1
          FROM public.user_item_instances uii
          WHERE uii.user_id = target_user_id
            AND uii.item_id = ai.id
      );

    INSERT INTO public.user_avatar_profile (user_id)
    VALUES (target_user_id)
    ON CONFLICT (user_id) DO NOTHING;
    GET DIAGNOSTICS created_profiles = ROW_COUNT;

    IF NOT EXISTS (SELECT 1 FROM public.user_outfit_items WHERE user_id = target_user_id) THEN
        INSERT INTO public.user_outfit_items (user_id, item_instance_id, item_id)
        SELECT DISTINCT ON (ai.id) target_user_id, uii.id, ai.id
        FROM public.avatar_items ai
        JOIN public.user_item_instances uii
          ON uii.item_id = ai.id
         AND uii.user_id = target_user_id
         AND uii.status = 'owned'
        WHERE ai.art_version = 2
          AND ai.is_default = TRUE
        ORDER BY ai.id, uii.id;
    END IF;

    IF created_profiles > 0 THEN
        PERFORM public.carry_over_legacy_avatar(target_user_id);
    END IF;
END;
$$;

DO $$
DECLARE
    fn TEXT;
BEGIN
    FOREACH fn IN ARRAY ARRAY[
        'public.carry_over_legacy_avatar(uuid)',
        'public.seed_user_avatar_defaults(uuid)'
    ]
    LOOP
        EXECUTE format('REVOKE EXECUTE ON FUNCTION %s FROM PUBLIC, anon, authenticated', fn);
        EXECUTE format('GRANT EXECUTE ON FUNCTION %s TO service_role', fn);
    END LOOP;
END;
$$;
