-- The shop's third round: 25 more avatar items (sunglasses, headphones, a backpack, a hoodie, overalls,
-- a raincoat, a crown, an owl, a little UFO, and more to hold), added if missing. And the things you hold
-- move out to the hand, now the arm swings out to the left to hold them: their parts' places and
-- icons are brought up to date. Rows from avatar_catalog.sql (made by npm run art:avatar). Run by
-- the server at start; harmless to run again.

INSERT INTO public.avatar_items (
    item_key, name, slot, equip_group, layer_order, asset_path,
    is_default, is_starter, is_tradeable, is_sellable, rarity, base_price, release_status,
    metadata, art_version, category, parts, dyes, hides, occupies, stack_order
)
VALUES
('backpack', 'Backpack', 'back', 'back', 0, '/avatar-px/items/backpack/icon.png?v=15a6759e0c', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'back', '[{"slot":"back","anchor":"body","x":17,"y":34,"w":4,"h":5,"frames":1,"src":"/avatar-px/items/backpack/0-back.png?v=71b8df0b59","fits":["body_kid"]}]'::jsonb, '{"dye1":"pine"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('balloon', 'Balloon', 'held', 'held', 0, '/avatar-px/items/balloon/icon.png?v=8dd1170f9e', false, false, true, true, 'common', 70, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":21,"w":5,"h":15,"frames":1,"src":"/avatar-px/items/balloon/0-held.png?v=69c304075e","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('bow_tie', 'Bow Tie', 'neck', 'neck', 0, '/avatar-px/items/bow_tie/icon.png?v=2cc4c81ea1', false, false, true, true, 'uncommon', 70, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'neck', '[{"slot":"neck","anchor":"body","x":13,"y":33,"w":5,"h":3,"frames":1,"src":"/avatar-px/items/bow_tie/0-neck.png?v=9336fb72f3","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('butterfly_wings', 'Butterfly Wings', 'wings', 'wings', 0, '/avatar-px/items/butterfly_wings/icon.png?v=d107ca1a3d', false, false, true, true, 'epic', 340, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'wings', '[{"slot":"wings","anchor":"body","x":5,"y":26,"w":22,"h":12,"frames":1,"src":"/avatar-px/items/butterfly_wings/0-wings.png?v=e4df955b6e","fits":["body_kid","body_ghost"]}]'::jsonb, '{"dye1":"rose","dye2":"cloud"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('crown', 'Crown', 'head', 'head', 0, '/avatar-px/items/crown/icon.png?v=a08d2d6843', false, false, true, true, 'legendary', 600, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":12,"y":21,"w":8,"h":3,"frames":1,"src":"/avatar-px/items/crown/0-head.png?v=ca9f54826c"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('fireflies', 'Fireflies', 'aura', 'aura', 0, '/avatar-px/items/fireflies/icon.png?v=f590760a1f', false, false, true, true, 'rare', 280, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"front_fx","anchor":"free","x":0,"y":16,"w":29,"h":30,"frames":6,"src":"/avatar-px/items/fireflies/0-front_fx.png?v=8c98072da2"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('fishing_rod', 'Fishing Rod', 'held', 'held', 0, '/avatar-px/items/fishing_rod/icon.png?v=3b852cf466', false, false, true, true, 'uncommon', 130, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":0,"y":19,"w":10,"h":22,"frames":1,"src":"/avatar-px/items/fishing_rod/0-held.png?v=c0bc6b8657","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('flashlight', 'Flashlight', 'held', 'held', 0, '/avatar-px/items/flashlight/icon.png?v=38509814f1', false, false, true, true, 'uncommon', 100, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":0,"y":34,"w":9,"h":6,"frames":1,"src":"/avatar-px/items/flashlight/0-held.png?v=60a7c90b9c","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('flip_flops', 'Flip-Flops', 'feet', 'feet', 0, '/avatar-px/items/flip_flops/icon.png?v=fb66588bbe', false, false, true, true, 'common', 40, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":45,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/flip_flops/0-feet.png?v=104c6b2f81","fits":["body_kid"]}]'::jsonb, '{"dye1":"teal"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('freckles', 'Freckles', 'face_paint', 'face_paint', 0, '/avatar-px/items/freckles/icon.png?v=43ec66196f', false, false, true, true, 'common', 30, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'face_paint', '[{"slot":"face_paint","anchor":"head","x":13,"y":31,"w":4,"h":2,"frames":1,"src":"/avatar-px/items/freckles/0-face_paint.png?v=9ccf98643c","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('frog', 'Frog', 'companion', 'companion', 0, '/avatar-px/items/frog/icon.png?v=388f722d1f', false, false, true, true, 'uncommon', 180, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":40,"w":7,"h":7,"frames":6,"src":"/avatar-px/items/frog/0-companion.png?v=7d92b71a26"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('headphones', 'Headphones', 'head', 'head', 0, '/avatar-px/items/headphones/icon.png?v=bc4fd9f853', false, false, true, true, 'rare', 160, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":10,"y":23,"w":12,"h":8,"frames":1,"src":"/avatar-px/items/headphones/0-head.png?v=2af5833c0c","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hoodie', 'Hoodie', 'torso', 'torso', 0, '/avatar-px/items/hoodie/icon.png?v=d2d8d6073d', false, false, true, true, 'uncommon', 130, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/hoodie/0-torso.png?v=618c4482be","fits":["body_kid"]}]'::jsonb, '{"dye1":"plum"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('little_ufo', 'Little UFO', 'companion', 'companion', 0, '/avatar-px/items/little_ufo/icon.png?v=a1b4772959', false, false, true, true, 'epic', 360, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":14,"w":9,"h":6,"frames":6,"src":"/avatar-px/items/little_ufo/0-companion.png?v=cf0c74f4eb"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('magic_wand', 'Magic Wand', 'held', 'held', 0, '/avatar-px/items/magic_wand/icon.png?v=21dfbee8eb', false, false, true, true, 'rare', 190, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":4,"y":27,"w":6,"h":9,"frames":6,"src":"/avatar-px/items/magic_wand/0-held.png?v=bc242ec919","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('overalls', 'Overalls', 'legs', 'legs', 0, '/avatar-px/items/overalls/icon.png?v=b8159cc12a', false, false, true, true, 'uncommon', 120, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/overalls/0-legs.png?v=85190ce4df","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":13,"y":41,"w":5,"h":4,"frames":1,"src":"/avatar-px/items/overalls/1-legs.png?v=eefc67b681","fits":["body_kid"]},{"slot":"outer","anchor":"body","x":14,"y":34,"w":3,"h":5,"frames":1,"src":"/avatar-px/items/overalls/2-outer.png?v=dc74142c84","fits":["body_kid"]}]'::jsonb, '{"dye1":"denim"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('owl', 'Owl', 'companion', 'companion', 0, '/avatar-px/items/owl/icon.png?v=4763d03a88', false, false, true, true, 'rare', 270, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":38,"w":7,"h":9,"frames":6,"src":"/avatar-px/items/owl/0-companion.png?v=df6657353b"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('party_hat', 'Party Hat', 'head', 'head', 0, '/avatar-px/items/party_hat/icon.png?v=8939086eed', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":13,"y":17,"w":7,"h":7,"frames":1,"src":"/avatar-px/items/party_hat/0-head.png?v=b68e30c1af"}]'::jsonb, '{"dye1":"teal","dye2":"orange"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('pizza_slice', 'Pizza Slice', 'held', 'held', 0, '/avatar-px/items/pizza_slice/icon.png?v=b18b7521d9', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":5,"y":34,"w":5,"h":4,"frames":1,"src":"/avatar-px/items/pizza_slice/0-held.png?v=49acb5a112","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('rain_boots', 'Rain Boots', 'feet', 'feet', 0, '/avatar-px/items/rain_boots/icon.png?v=bd4aa6bbeb', false, false, true, true, 'uncommon', 80, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":42,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/rain_boots/0-feet.png?v=b65479ca72","fits":["body_kid"]}]'::jsonb, '{"dye1":"mustard"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('raincoat', 'Raincoat', 'outer', 'outer', 0, '/avatar-px/items/raincoat/icon.png?v=0fd8ca4e7f', false, false, true, true, 'uncommon', 140, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'outer', '[{"slot":"outer","anchor":"body","x":12,"y":33,"w":7,"h":7,"frames":1,"src":"/avatar-px/items/raincoat/0-outer.png?v=2054844f93","fits":["body_kid"]}]'::jsonb, '{"dye1":"mustard"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('skateboard', 'Skateboard', 'held', 'held', 0, '/avatar-px/items/skateboard/icon.png?v=1396893d87', false, false, true, true, 'uncommon', 120, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":29,"w":3,"h":13,"frames":1,"src":"/avatar-px/items/skateboard/0-held.png?v=c328aef160","fits":["body_kid"]}]'::jsonb, '{"dye1":"lime"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('sunglasses', 'Sunglasses', 'face_acc', 'face_acc', 0, '/avatar-px/items/sunglasses/icon.png?v=101202a353', false, false, true, true, 'uncommon', 80, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'face_acc', '[{"slot":"face_acc","anchor":"head","x":10,"y":29,"w":10,"h":3,"frames":1,"src":"/avatar-px/items/sunglasses/0-face_acc.png?v=6a0e9c7f96","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('teddy_bear', 'Teddy Bear', 'held', 'held', 0, '/avatar-px/items/teddy_bear/icon.png?v=a5512e81e4', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":4,"y":36,"w":6,"h":7,"frames":1,"src":"/avatar-px/items/teddy_bear/0-held.png?v=2c865966bd","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('umbrella', 'Umbrella', 'held', 'held', 0, '/avatar-px/items/umbrella/icon.png?v=d4b5b68ca2', false, false, true, true, 'rare', 200, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":3,"y":19,"w":13,"h":19,"frames":1,"src":"/avatar-px/items/umbrella/0-held.png?v=ba80adafb0","fits":["body_kid"]}]'::jsonb, '{"dye1":"ocean"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0)
ON CONFLICT (item_key) DO NOTHING;

INSERT INTO public.avatar_items (
    item_key, name, slot, equip_group, layer_order, asset_path,
    is_default, is_starter, is_tradeable, is_sellable, rarity, base_price, release_status,
    metadata, art_version, category, parts, dyes, hides, occupies, stack_order
)
VALUES
('candlestick', 'Candlestick', 'held', 'held', 0, '/avatar-px/items/candlestick/icon.png?v=9c1a127278', false, false, true, true, 'uncommon', 120, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":31,"w":4,"h":7,"frames":5,"src":"/avatar-px/items/candlestick/0-held.png?v=4cdc729673","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('candy_pail', 'Candy Pail', 'held', 'held', 0, '/avatar-px/items/candy_pail/icon.png?v=e166944520', false, false, true, true, 'rare', 160, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":5,"y":37,"w":8,"h":8,"frames":1,"src":"/avatar-px/items/candy_pail/0-held.png?v=9a8e942aa3","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('caramel_apple', 'Caramel Apple', 'held', 'held', 0, '/avatar-px/items/caramel_apple/icon.png?v=4cb8f5012d', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":32,"w":5,"h":6,"frames":1,"src":"/avatar-px/items/caramel_apple/0-held.png?v=d54da01971","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('grim_scythe', 'Grim Scythe', 'held', 'held', 0, '/avatar-px/items/grim_scythe/icon.png?v=ae371125fb', false, false, true, true, 'epic', 380, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":0,"y":19,"w":10,"h":27,"frames":1,"src":"/avatar-px/items/grim_scythe/0-held.png?v=f48c0fcd09","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hot_cider', 'Hot Cider', 'held', 'held', 0, '/avatar-px/items/hot_cider/icon.png?v=43e0496d34', false, false, true, true, 'common', 70, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":5,"y":33,"w":5,"h":6,"frames":5,"src":"/avatar-px/items/hot_cider/0-held.png?v=2ebf8b67be","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('leaf_rake', 'Leaf Rake', 'held', 'held', 0, '/avatar-px/items/leaf_rake/icon.png?v=e69bfe3cbc', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":6,"y":19,"w":7,"h":27,"frames":1,"src":"/avatar-px/items/leaf_rake/0-held.png?v=777844cba0","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('purdue_pennant', 'Purdue Pennant', 'held', 'held', 0, '/avatar-px/items/purdue_pennant/icon.png?v=cd3574c76c', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":1,"y":31,"w":9,"h":9,"frames":3,"src":"/avatar-px/items/purdue_pennant/0-held.png?v=f4f73bcd70","fits":["body_kid"]}]'::jsonb, '{"dye1":"coal"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('rocket_pop', 'Rocket Pop', 'held', 'held', 0, '/avatar-px/items/rocket_pop/icon.png?v=cc87690aee', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":8,"y":30,"w":3,"h":7,"frames":1,"src":"/avatar-px/items/rocket_pop/0-held.png?v=9c0172db03","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('soda_pop', 'Soda Pop', 'held', 'held', 0, '/avatar-px/items/soda_pop/icon.png?v=58f33e8eaa', false, false, true, true, 'common', 50, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":33,"w":3,"h":6,"frames":1,"src":"/avatar-px/items/soda_pop/0-held.png?v=555fc4f3df","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('soul_lantern_px', 'Lantern', 'held', 'held', 0, '/avatar-px/items/soul_lantern_px/icon.png?v=8e7e9a679e', false, false, true, true, 'epic', 300, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":38,"w":6,"h":7,"frames":5,"src":"/avatar-px/items/soul_lantern_px/0-held.png?v=f094e0756f","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('witch_broom', 'Witch''s Broom', 'held', 'held', 0, '/avatar-px/items/witch_broom/icon.png?v=df107ff950', false, false, true, true, 'rare', 240, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":21,"w":5,"h":25,"frames":1,"src":"/avatar-px/items/witch_broom/0-held.png?v=7eedf26d8f","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0)
ON CONFLICT (item_key) DO UPDATE SET
    asset_path = EXCLUDED.asset_path,
    parts = EXCLUDED.parts
WHERE public.avatar_items.art_version = 3;
