-- More of the shop moves: hair that swings and bounces, wings that flap, a cape's hem, a tail, scarf ends,
-- a halo, a crown's stones, a balloon, a glint on sunglasses. Each item's redrawn strips (more frames, under
-- new addresses so nobody keeps the old ones cached). Rows from avatar_catalog.sql (npm run art:avatar).
-- Run by the server at start; harmless to run again.

UPDATE public.avatar_items SET asset_path = '/avatar-px/items/balloon/icon.png?v=8dd1170f9e', parts = '[{"slot":"held","anchor":"body","x":7,"y":20,"w":5,"h":16,"frames":4,"src":"/avatar-px/items/balloon/0-held.png?v=ea9e6be72a","fits":["body_kid"]}]'::jsonb WHERE item_key = 'balloon';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/bone_wings/icon.png?v=b821278b1f', parts = '[{"slot":"wings","anchor":"body","x":4,"y":25,"w":24,"h":10,"frames":5,"src":"/avatar-px/items/bone_wings/0-wings.png?v=a469b5834a","fits":["body_kid","body_ghost"]}]'::jsonb WHERE item_key = 'bone_wings';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/butterfly_wings/icon.png?v=d107ca1a3d', parts = '[{"slot":"wings","anchor":"body","x":5,"y":26,"w":22,"h":12,"frames":5,"src":"/avatar-px/items/butterfly_wings/0-wings.png?v=de6d6af5df","fits":["body_kid","body_ghost"]}]'::jsonb WHERE item_key = 'butterfly_wings';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/chunky_scarf/icon.png?v=c9c9f702b3', parts = '[{"slot":"neck","anchor":"body","x":11,"y":33,"w":10,"h":7,"frames":5,"src":"/avatar-px/items/chunky_scarf/0-neck.png?v=e5c3c2ad8f","fits":["body_kid"]}]'::jsonb WHERE item_key = 'chunky_scarf';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/crown/icon.png?v=a08d2d6843', parts = '[{"slot":"head","anchor":"head","x":12,"y":21,"w":8,"h":3,"frames":5,"src":"/avatar-px/items/crown/0-head.png?v=5c4261510e"}]'::jsonb WHERE item_key = 'crown';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/devil_tail/icon.png?v=a4054062fe', parts = '[{"slot":"back","anchor":"body","x":18,"y":35,"w":6,"h":7,"frames":6,"src":"/avatar-px/items/devil_tail/0-back.png?v=0b07a418c4","fits":["body_kid"]}]'::jsonb WHERE item_key = 'devil_tail';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/fairy_wings/icon.png?v=ab74bd95ca', parts = '[{"slot":"wings","anchor":"body","x":4,"y":25,"w":24,"h":10,"frames":6,"src":"/avatar-px/items/fairy_wings/0-wings.png?v=588e843e71","fits":["body_kid","body_ghost"]}]'::jsonb WHERE item_key = 'fairy_wings';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/gold_chain/icon.png?v=bcf93cf6db', parts = '[{"slot":"neck","anchor":"body","x":13,"y":33,"w":5,"h":3,"frames":5,"src":"/avatar-px/items/gold_chain/0-neck.png?v=18fcac63b8","fits":["body_kid"]}]'::jsonb WHERE item_key = 'gold_chain';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/hair_afro/icon.png?v=f3b9a11599', parts = '[{"slot":"hair","anchor":"head","x":9,"y":19,"w":14,"h":11,"frames":5,"src":"/avatar-px/items/hair_afro/0-hair.png?v=cb379ed293","fits":["body_kid"]}]'::jsonb WHERE item_key = 'hair_afro';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/hair_bob/icon.png?v=e026d5e55a', parts = '[{"slot":"hair","anchor":"head","x":11,"y":23,"w":11,"h":10,"frames":4,"src":"/avatar-px/items/hair_bob/0-hair.png?v=89ab949e19","fits":["body_kid"]}]'::jsonb WHERE item_key = 'hair_bob';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/hair_curls/icon.png?v=3f0e23800f', parts = '[{"slot":"hair","anchor":"head","x":9,"y":19,"w":14,"h":13,"frames":5,"src":"/avatar-px/items/hair_curls/0-hair.png?v=cd9e5319dd","fits":["body_kid"]}]'::jsonb WHERE item_key = 'hair_curls';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/hair_long_straight/icon.png?v=cac7921a58', parts = '[{"slot":"hair","anchor":"head","x":10,"y":23,"w":13,"h":14,"frames":5,"src":"/avatar-px/items/hair_long_straight/0-hair.png?v=6689c9749a","fits":["body_kid"]}]'::jsonb WHERE item_key = 'hair_long_straight';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/hair_pigtails/icon.png?v=013bef0817', parts = '[{"slot":"hair","anchor":"head","x":9,"y":24,"w":14,"h":9,"frames":5,"src":"/avatar-px/items/hair_pigtails/0-hair.png?v=dbc6cb363b","fits":["body_kid"]}]'::jsonb WHERE item_key = 'hair_pigtails';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/hair_space_buns/icon.png?v=5bedbc7cda', parts = '[{"slot":"hair","anchor":"head","x":10,"y":20,"w":13,"h":13,"frames":5,"src":"/avatar-px/items/hair_space_buns/0-hair.png?v=94daadba24","fits":["body_kid"]}]'::jsonb WHERE item_key = 'hair_space_buns';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/hair_spikes/icon.png?v=af244e4f5a', parts = '[{"slot":"hair","anchor":"head","x":11,"y":20,"w":11,"h":13,"frames":6,"src":"/avatar-px/items/hair_spikes/0-hair.png?v=093c5f6acc","fits":["body_kid"]}]'::jsonb WHERE item_key = 'hair_spikes';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/hair_top_bun/icon.png?v=16c34770e7', parts = '[{"slot":"hair","anchor":"head","x":11,"y":21,"w":10,"h":9,"frames":4,"src":"/avatar-px/items/hair_top_bun/0-hair.png?v=7907525c45","fits":["body_kid"]}]'::jsonb WHERE item_key = 'hair_top_bun';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/halo/icon.png?v=ef75109000', parts = '[{"slot":"head","anchor":"head","x":11,"y":18,"w":8,"h":5,"frames":6,"src":"/avatar-px/items/halo/0-head.png?v=ba132de0a5"}]'::jsonb WHERE item_key = 'halo';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/party_hat/icon.png?v=8939086eed', parts = '[{"slot":"head","anchor":"head","x":13,"y":17,"w":7,"h":7,"frames":6,"src":"/avatar-px/items/party_hat/0-head.png?v=c52850114c"}]'::jsonb WHERE item_key = 'party_hat';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/pointy_witch_hat/icon.png?v=458e23addc', parts = '[{"slot":"head","anchor":"head","x":7,"y":14,"w":18,"h":13,"frames":4,"src":"/avatar-px/items/pointy_witch_hat/0-head.png?v=a2f943c644"}]'::jsonb WHERE item_key = 'pointy_witch_hat';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/striped_scarf/icon.png?v=163c9700e4', parts = '[{"slot":"neck","anchor":"body","x":12,"y":33,"w":9,"h":7,"frames":5,"src":"/avatar-px/items/striped_scarf/0-neck.png?v=aab5b73434","fits":["body_kid"]}]'::jsonb WHERE item_key = 'striped_scarf';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/sunglasses/icon.png?v=101202a353', parts = '[{"slot":"face_acc","anchor":"head","x":10,"y":29,"w":10,"h":3,"frames":5,"src":"/avatar-px/items/sunglasses/0-face_acc.png?v=bce86f33cd","fits":["body_kid"]}]'::jsonb WHERE item_key = 'sunglasses';
UPDATE public.avatar_items SET asset_path = '/avatar-px/items/vampire_cape/icon.png?v=bfb322deb6', parts = '[{"slot":"back","anchor":"body","x":10,"y":33,"w":13,"h":12,"frames":4,"src":"/avatar-px/items/vampire_cape/0-back.png?v=34a26f86e1","fits":["body_kid"]},{"slot":"neck","anchor":"body","x":10,"y":29,"w":11,"h":4,"frames":1,"src":"/avatar-px/items/vampire_cape/1-neck.png?v=a475afb8e5","fits":["body_kid"]}]'::jsonb WHERE item_key = 'vampire_cape';
