-- Two more avatar items in every category (bodies, face paint, hair, hats, masks and glasses, neck,
-- tops, jackets, bottoms, shoes, back, wings, held, pets and auras), added if missing. Rows from
-- avatar_catalog.sql (made by npm run art:avatar). Run by the server at start; harmless to run again.

INSERT INTO public.avatar_items (
    item_key, name, slot, equip_group, layer_order, asset_path,
    is_default, is_starter, is_tradeable, is_sellable, rarity, base_price, release_status,
    metadata, art_version, category, parts, dyes, hides, occupies, stack_order
)
VALUES
('bandana', 'Bandana', 'neck', 'neck', 0, '/avatar-px/items/bandana/icon.png?v=ec61e25596', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'neck', '[{"slot":"neck","anchor":"body","x":12,"y":33,"w":7,"h":4,"frames":1,"src":"/avatar-px/items/bandana/0-neck.png?v=4cad36b9d4","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('baseball_cap', 'Baseball Cap', 'head', 'head', 0, '/avatar-px/items/baseball_cap/icon.png?v=77bc4e9246', false, false, true, true, 'common', 70, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":11,"y":23,"w":12,"h":4,"frames":1,"src":"/avatar-px/items/baseball_cap/0-head.png?v=17eca56967"}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('body_crow', 'Crow', 'body', 'body', 0, '/avatar-px/items/body_crow/icon.png?v=b484b11d5f', false, false, true, true, 'rare', 320, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'body', '[{"slot":"body","anchor":"ground","x":8,"y":32,"w":16,"h":16,"frames":8,"src":"/avatar-px/items/body_crow/0-body.png?v=93555499e1"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('body_warrior', 'Jaguar Warrior', 'body', 'body', 0, '/avatar-px/items/body_warrior/icon.png?v=4523f16f3f', false, false, true, true, 'epic', 500, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'body', '[{"slot":"body","anchor":"ground","x":8,"y":24,"w":17,"h":23,"frames":5,"src":"/avatar-px/items/body_warrior/0-body.png?v=4f7d69ff2d"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('bone_wings', 'Bone Wings', 'wings', 'wings', 0, '/avatar-px/items/bone_wings/icon.png?v=b821278b1f', false, false, true, true, 'epic', 340, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'wings', '[{"slot":"wings","anchor":"body","x":4,"y":25,"w":24,"h":9,"frames":1,"src":"/avatar-px/items/bone_wings/0-wings.png?v=cedbba5a8c","fits":["body_kid","body_ghost"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('bubbles', 'Bubbles', 'aura', 'aura', 0, '/avatar-px/items/bubbles/icon.png?v=393d87f519', false, false, true, true, 'uncommon', 200, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"front_fx","anchor":"free","x":1,"y":16,"w":30,"h":30,"frames":6,"src":"/avatar-px/items/bubbles/0-front_fx.png?v=f9116df445"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('bunny', 'Bunny', 'companion', 'companion', 0, '/avatar-px/items/bunny/icon.png?v=809f2f5f79', false, false, true, true, 'rare', 240, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":38,"w":7,"h":9,"frames":6,"src":"/avatar-px/items/bunny/0-companion.png?v=81e91ec95b"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('burning_torch', 'Burning Torch', 'held', 'held', 0, '/avatar-px/items/burning_torch/icon.png?v=1b0e8626d7', false, false, true, true, 'rare', 180, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":24,"w":4,"h":13,"frames":6,"src":"/avatar-px/items/burning_torch/0-held.png?v=c25d68cb50","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('chefs_hat', 'Chef''s Hat', 'head', 'head', 0, '/avatar-px/items/chefs_hat/icon.png?v=70ad5f2ac8', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":11,"y":17,"w":9,"h":9,"frames":1,"src":"/avatar-px/items/chefs_hat/0-head.png?v=edd0f24caf"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('clown_shoes', 'Clown Shoes', 'feet', 'feet', 0, '/avatar-px/items/clown_shoes/icon.png?v=5ce943b678', false, false, true, true, 'rare', 150, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":10,"y":44,"w":10,"h":3,"frames":1,"src":"/avatar-px/items/clown_shoes/0-feet.png?v=d7ff111ead","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('fairy_wings', 'Fairy Wings', 'wings', 'wings', 0, '/avatar-px/items/fairy_wings/icon.png?v=ab74bd95ca', false, false, true, true, 'epic', 320, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'wings', '[{"slot":"wings","anchor":"body","x":4,"y":25,"w":24,"h":10,"frames":1,"src":"/avatar-px/items/fairy_wings/0-wings.png?v=25b595376d","fits":["body_kid","body_ghost"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('floating_hearts', 'Floating Hearts', 'aura', 'aura', 0, '/avatar-px/items/floating_hearts/icon.png?v=a1cc826c65', false, false, true, true, 'rare', 260, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"front_fx","anchor":"free","x":1,"y":16,"w":30,"h":30,"frames":6,"src":"/avatar-px/items/floating_hearts/0-front_fx.png?v=3d5494b60a"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('gold_chain', 'Gold Chain', 'neck', 'neck', 0, '/avatar-px/items/gold_chain/icon.png?v=bcf93cf6db', false, false, true, true, 'rare', 160, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'neck', '[{"slot":"neck","anchor":"body","x":13,"y":33,"w":5,"h":3,"frames":1,"src":"/avatar-px/items/gold_chain/0-neck.png?v=45ffe1f8d4","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hair_afro', 'Afro', 'hair', 'hair', 0, '/avatar-px/items/hair_afro/icon.png?v=f3b9a11599', false, true, false, false, 'common', NULL, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'hair', '[{"slot":"hair","anchor":"head","x":9,"y":20,"w":14,"h":10,"frames":1,"src":"/avatar-px/items/hair_afro/0-hair.png?v=3cb2968f61","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hair_pompadour', 'Pompadour', 'hair', 'hair', 0, '/avatar-px/items/hair_pompadour/icon.png?v=fa63296bc4', false, true, false, false, 'common', NULL, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'hair', '[{"slot":"hair","anchor":"head","x":11,"y":21,"w":10,"h":6,"frames":1,"src":"/avatar-px/items/hair_pompadour/0-hair.png?v=87e8de870c","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hero_tee', 'Hero Tee', 'torso', 'torso', 0, '/avatar-px/items/hero_tee/icon.png?v=43347c50d3', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/hero_tee/0-torso.png?v=3246439772","fits":["body_kid"]}]'::jsonb, '{"dye1":"ocean"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('jetpack', 'Jetpack', 'back', 'back', 0, '/avatar-px/items/jetpack/icon.png?v=6af9951f5a', false, false, true, true, 'epic', 380, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'back', '[{"slot":"back","anchor":"body","x":17,"y":33,"w":4,"h":7,"frames":6,"src":"/avatar-px/items/jetpack/0-back.png?v=dac215bd1a","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('kilt', 'Kilt', 'legs', 'legs', 0, '/avatar-px/items/kilt/icon.png?v=4d41979ae6', false, false, true, true, 'uncommon', 100, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/kilt/0-legs.png?v=85190ce4df","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":12,"y":41,"w":7,"h":3,"frames":1,"src":"/avatar-px/items/kilt/1-legs.png?v=490c0fa006","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry","dye2":"pine"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('lab_coat', 'Lab Coat', 'outer', 'outer', 0, '/avatar-px/items/lab_coat/icon.png?v=530f6fd5e6', false, false, true, true, 'uncommon', 130, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'outer', '[{"slot":"outer","anchor":"body","x":12,"y":33,"w":8,"h":7,"frames":1,"src":"/avatar-px/items/lab_coat/0-outer.png?v=7cce016f83","fits":["body_kid"]}]'::jsonb, '{"dye2":"ocean"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('leather_jacket', 'Leather Jacket', 'outer', 'outer', 0, '/avatar-px/items/leather_jacket/icon.png?v=2b43cce5c8', false, false, true, true, 'rare', 190, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'outer', '[{"slot":"outer","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/leather_jacket/0-outer.png?v=3eaadd57ae","fits":["body_kid"]}]'::jsonb, '{"dye1":"coal","dye2":"ash"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('lollipop', 'Lollipop', 'held', 'held', 0, '/avatar-px/items/lollipop/icon.png?v=29ef798244', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":27,"w":4,"h":10,"frames":1,"src":"/avatar-px/items/lollipop/0-held.png?v=81763e3676","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('monocle', 'Monocle', 'face_acc', 'face_acc', 0, '/avatar-px/items/monocle/icon.png?v=ef034469a9', false, false, true, true, 'rare', 150, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'face_acc', '[{"slot":"face_acc","anchor":"head","x":17,"y":28,"w":3,"h":5,"frames":1,"src":"/avatar-px/items/monocle/0-face_acc.png?v=ec2db4dd93","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('quiver', 'Quiver', 'back', 'back', 0, '/avatar-px/items/quiver/icon.png?v=0a62f234d6', false, false, true, true, 'uncommon', 120, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'back', '[{"slot":"back","anchor":"body","x":17,"y":31,"w":4,"h":7,"frames":1,"src":"/avatar-px/items/quiver/0-back.png?v=a7eda74ee6","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('snail', 'Snail', 'companion', 'companion', 0, '/avatar-px/items/snail/icon.png?v=b88cf62f44', false, false, true, true, 'uncommon', 150, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":43,"w":8,"h":4,"frames":6,"src":"/avatar-px/items/snail/0-companion.png?v=4718d83121"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('snow_boots', 'Snow Boots', 'feet', 'feet', 0, '/avatar-px/items/snow_boots/icon.png?v=4bc3e8e3f3', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":42,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/snow_boots/0-feet.png?v=5d0baae734","fits":["body_kid"]}]'::jsonb, '{"dye1":"ocean"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('space_suit_top', 'Space Suit Top', 'torso', 'torso', 0, '/avatar-px/items/space_suit_top/icon.png?v=18f08a4531', false, false, true, true, 'rare', 170, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/space_suit_top/0-torso.png?v=4e34853ab4","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('sweatpants', 'Sweatpants', 'legs', 'legs', 0, '/avatar-px/items/sweatpants/icon.png?v=d0b110b4a8', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/sweatpants/0-legs.png?v=c324638d5d","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":13,"y":41,"w":5,"h":4,"frames":1,"src":"/avatar-px/items/sweatpants/1-legs.png?v=b834595bfe","fits":["body_kid"]}]'::jsonb, '{"dye1":"ash"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('tear_drops', 'Tear Drops', 'face_paint', 'face_paint', 0, '/avatar-px/items/tear_drops/icon.png?v=c177947add', false, false, true, true, 'common', 40, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'face_paint', '[{"slot":"face_paint","anchor":"head","x":15,"y":32,"w":4,"h":1,"frames":1,"src":"/avatar-px/items/tear_drops/0-face_paint.png?v=5ae6952d72","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('three_d_glasses', '3D Glasses', 'face_acc', 'face_acc', 0, '/avatar-px/items/three_d_glasses/icon.png?v=a899e60fc9', false, false, true, true, 'uncommon', 80, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'face_acc', '[{"slot":"face_acc","anchor":"head","x":10,"y":29,"w":10,"h":3,"frames":1,"src":"/avatar-px/items/three_d_glasses/0-face_acc.png?v=0f6e6554bd","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('war_paint', 'War Paint', 'face_paint', 'face_paint', 0, '/avatar-px/items/war_paint/icon.png?v=51b3d07a65', false, false, true, true, 'uncommon', 70, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'face_paint', '[{"slot":"face_paint","anchor":"head","x":14,"y":32,"w":5,"h":1,"frames":1,"src":"/avatar-px/items/war_paint/0-face_paint.png?v=f96607fdba","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0)
ON CONFLICT (item_key) DO NOTHING;
