-- Ten more common avatar items for the capsule machine (and the shop): five hats and five things
-- to hold, added if missing. Rows from avatar_catalog.sql (made by npm run art:avatar). Run by the
-- server at start; harmless to run again.

INSERT INTO public.avatar_items (
    item_key, name, slot, equip_group, layer_order, asset_path,
    is_default, is_starter, is_tradeable, is_sellable, rarity, base_price, release_status,
    metadata, art_version, category, parts, dyes, hides, occupies, stack_order
)
VALUES
('baguette', 'Baguette', 'held', 'held', 0, '/avatar-px/items/baguette/icon.png?v=7586ac8e3f', false, false, true, true, 'common', 50, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":27,"w":3,"h":9,"frames":1,"src":"/avatar-px/items/baguette/0-held.png?v=8e99f37968","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('bubble_wand', 'Bubble Wand', 'held', 'held', 0, '/avatar-px/items/bubble_wand/icon.png?v=e0abeea584', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":25,"w":4,"h":11,"frames":5,"src":"/avatar-px/items/bubble_wand/0-held.png?v=7f69079499","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('flat_cap', 'Flat Cap', 'head', 'head', 0, '/avatar-px/items/flat_cap/icon.png?v=c5ac90bb40', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":11,"y":23,"w":11,"h":3,"frames":1,"src":"/avatar-px/items/flat_cap/0-head.png?v=6d8660d17e"}]'::jsonb, '{"dye1":"bark"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hair_bow', 'Hair Bow', 'head', 'head', 0, '/avatar-px/items/hair_bow/icon.png?v=556ffacb98', false, false, true, true, 'common', 50, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":12,"y":22,"w":7,"h":3,"frames":1,"src":"/avatar-px/items/hair_bow/0-head.png?v=0d312b1752"}]'::jsonb, '{"dye1":"rose"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('knit_beanie', 'Knit Beanie', 'head', 'head', 0, '/avatar-px/items/knit_beanie/icon.png?v=5bcc83c715', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":11,"y":22,"w":9,"h":4,"frames":1,"src":"/avatar-px/items/knit_beanie/0-head.png?v=cbcda41b83","fits":["body_kid"]}]'::jsonb, '{"dye1":"denim"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('little_flag', 'Little Flag', 'held', 'held', 0, '/avatar-px/items/little_flag/icon.png?v=d075ebad2d', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":6,"y":26,"w":4,"h":10,"frames":4,"src":"/avatar-px/items/little_flag/0-held.png?v=49a6d96287","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('magnifying_glass', 'Magnifying Glass', 'held', 'held', 0, '/avatar-px/items/magnifying_glass/icon.png?v=b77b642452', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":29,"w":4,"h":7,"frames":1,"src":"/avatar-px/items/magnifying_glass/0-held.png?v=c18407f165","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('paper_plane', 'Paper Plane', 'held', 'held', 0, '/avatar-px/items/paper_plane/icon.png?v=807a86e206', false, false, true, true, 'common', 50, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":4,"y":33,"w":7,"h":4,"frames":1,"src":"/avatar-px/items/paper_plane/0-held.png?v=25eb1c8bda","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('spotted_bandana', 'Spotted Bandana', 'head', 'head', 0, '/avatar-px/items/spotted_bandana/icon.png?v=eb79c1b9b8', false, false, true, true, 'common', 50, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":10,"y":23,"w":10,"h":4,"frames":1,"src":"/avatar-px/items/spotted_bandana/0-head.png?v=e245b6d9a1","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('traffic_cone', 'Traffic Cone', 'head', 'head', 0, '/avatar-px/items/traffic_cone/icon.png?v=cfb1f48a8d', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":11,"y":18,"w":10,"h":7,"frames":1,"src":"/avatar-px/items/traffic_cone/0-head.png?v=a99ca44f32"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0)
ON CONFLICT (item_key) DO NOTHING;
