-- The shop's fourth round: 17 more avatar items (shoes: high-tops, cowboy boots, bunny slippers,
-- roller skates, striped socks; bottoms: shorts, a skirt, ripped jeans, pyjamas, a tutu, bell-bottoms;
-- auras: falling leaves, snow, starlight, music notes, a raincloud, hellfire), added if missing.
-- Rows from avatar_catalog.sql (made by npm run art:avatar). Run by the server at start; harmless
-- to run again.

INSERT INTO public.avatar_items (
    item_key, name, slot, equip_group, layer_order, asset_path,
    is_default, is_starter, is_tradeable, is_sellable, rarity, base_price, release_status,
    metadata, art_version, category, parts, dyes, hides, occupies, stack_order
)
VALUES
('bell_bottoms', 'Bell-Bottoms', 'legs', 'legs', 0, '/avatar-px/items/bell_bottoms/icon.png?v=01f2dab042', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/bell_bottoms/0-legs.png?v=85190ce4df","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":12,"y":41,"w":7,"h":4,"frames":1,"src":"/avatar-px/items/bell_bottoms/1-legs.png?v=bdf90b705a","fits":["body_kid"]}]'::jsonb, '{"dye1":"teal"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('bunny_slippers', 'Bunny Slippers', 'feet', 'feet', 0, '/avatar-px/items/bunny_slippers/icon.png?v=9c45196bca', false, false, true, true, 'rare', 140, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":44,"w":7,"h":3,"frames":1,"src":"/avatar-px/items/bunny_slippers/0-feet.png?v=8fbee4b4f1","fits":["body_kid"]}]'::jsonb, '{"dye1":"rose"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('cargo_shorts', 'Cargo Shorts', 'legs', 'legs', 0, '/avatar-px/items/cargo_shorts/icon.png?v=78e2f02232', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/cargo_shorts/0-legs.png?v=85190ce4df","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":13,"y":41,"w":5,"h":2,"frames":1,"src":"/avatar-px/items/cargo_shorts/1-legs.png?v=1c98e05e26","fits":["body_kid"]}]'::jsonb, '{"dye1":"mustard"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('cowboy_boots', 'Cowboy Boots', 'feet', 'feet', 0, '/avatar-px/items/cowboy_boots/icon.png?v=66cf3387ad', false, false, true, true, 'rare', 150, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":42,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/cowboy_boots/0-feet.png?v=f429b17963","fits":["body_kid"]}]'::jsonb, '{"dye1":"bark"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('falling_leaves', 'Falling Leaves', 'aura', 'aura', 0, '/avatar-px/items/falling_leaves/icon.png?v=aafff03fcd', false, false, true, true, 'rare', 260, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"front_fx","anchor":"free","x":1,"y":16,"w":30,"h":30,"frames":6,"src":"/avatar-px/items/falling_leaves/0-front_fx.png?v=7513b17d1d"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hellfire', 'Hellfire', 'aura', 'aura', 0, '/avatar-px/items/hellfire/icon.png?v=491343454c', false, false, true, true, 'legendary', 520, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"back_fx","anchor":"free","x":0,"y":12,"w":23,"h":36,"frames":6,"src":"/avatar-px/items/hellfire/0-back_fx.png?v=66677420b0"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('high_tops', 'High-Tops', 'feet', 'feet', 0, '/avatar-px/items/high_tops/icon.png?v=bf3c211fec', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":43,"w":7,"h":4,"frames":1,"src":"/avatar-px/items/high_tops/0-feet.png?v=15a70be500","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('music_notes', 'Music Notes', 'aura', 'aura', 0, '/avatar-px/items/music_notes/icon.png?v=2af0f2fbc7', false, false, true, true, 'rare', 300, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"front_fx","anchor":"free","x":1,"y":16,"w":30,"h":30,"frames":6,"src":"/avatar-px/items/music_notes/0-front_fx.png?v=3423da8805"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('pleated_skirt', 'Pleated Skirt', 'legs', 'legs', 0, '/avatar-px/items/pleated_skirt/icon.png?v=84f70e9be1', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/pleated_skirt/0-legs.png?v=85190ce4df","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":12,"y":41,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/pleated_skirt/1-legs.png?v=2ae022fbb8","fits":["body_kid"]}]'::jsonb, '{"dye1":"plum"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('pyjama_bottoms', 'Pyjama Bottoms', 'legs', 'legs', 0, '/avatar-px/items/pyjama_bottoms/icon.png?v=07e99fd192', false, false, true, true, 'common', 70, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/pyjama_bottoms/0-legs.png?v=85190ce4df","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":13,"y":41,"w":5,"h":4,"frames":1,"src":"/avatar-px/items/pyjama_bottoms/1-legs.png?v=940657efe2","fits":["body_kid"]}]'::jsonb, '{"dye1":"ocean","dye2":"ash"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('raincloud', 'Raincloud', 'aura', 'aura', 0, '/avatar-px/items/raincloud/icon.png?v=8e8a713c99', false, false, true, true, 'epic', 420, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"back_fx","anchor":"free","x":6,"y":9,"w":19,"h":23,"frames":6,"src":"/avatar-px/items/raincloud/0-back_fx.png?v=22bcd27f60"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('ripped_jeans', 'Ripped Jeans', 'legs', 'legs', 0, '/avatar-px/items/ripped_jeans/icon.png?v=109accac55', false, false, true, true, 'uncommon', 100, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/ripped_jeans/0-legs.png?v=85190ce4df","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":13,"y":41,"w":5,"h":4,"frames":1,"src":"/avatar-px/items/ripped_jeans/1-legs.png?v=ba71450e19","fits":["body_kid"]}]'::jsonb, '{"dye1":"denim"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('roller_skates', 'Roller Skates', 'feet', 'feet', 0, '/avatar-px/items/roller_skates/icon.png?v=62962bfce2', false, false, true, true, 'rare', 170, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":43,"w":7,"h":4,"frames":1,"src":"/avatar-px/items/roller_skates/0-feet.png?v=4f951b7685","fits":["body_kid"]}]'::jsonb, '{"dye1":"teal"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('snow_flurry', 'Snow Flurry', 'aura', 'aura', 0, '/avatar-px/items/snow_flurry/icon.png?v=7457400901', false, false, true, true, 'rare', 280, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"front_fx","anchor":"free","x":1,"y":16,"w":30,"h":30,"frames":6,"src":"/avatar-px/items/snow_flurry/0-front_fx.png?v=8965bc440f"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('starlight', 'Starlight', 'aura', 'aura', 0, '/avatar-px/items/starlight/icon.png?v=defc85ff17', false, false, true, true, 'epic', 380, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"front_fx","anchor":"free","x":1,"y":15,"w":30,"h":30,"frames":6,"src":"/avatar-px/items/starlight/0-front_fx.png?v=a5a5428dda"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('striped_socks', 'Striped Socks', 'feet', 'feet', 0, '/avatar-px/items/striped_socks/icon.png?v=95f842ac34', false, false, true, true, 'common', 50, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'feet', '[{"slot":"feet","anchor":"ground","x":12,"y":42,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/striped_socks/0-feet.png?v=173b2b47ab","fits":["body_kid"]}]'::jsonb, '{"dye1":"plum","dye2":"lime"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('tutu', 'Tutu', 'legs', 'legs', 0, '/avatar-px/items/tutu/icon.png?v=76df36b9f2', false, false, true, true, 'rare', 160, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/tutu/0-legs.png?v=85190ce4df","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":11,"y":40,"w":9,"h":3,"frames":1,"src":"/avatar-px/items/tutu/1-legs.png?v=f73011422b","fits":["body_kid"]}]'::jsonb, '{"dye1":"rose"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0)
ON CONFLICT (item_key) DO NOTHING;
