-- The shop's second round: 39 new avatar items (Halloween, fall and summer things, cryptids, four more
-- 8 Bit Evil Returns enemies to be, and five free hair styles, Bald among them). Their rows from
-- avatar_catalog.sql (made by npm run art:avatar), added if missing. Run by the server at start;
-- harmless to run again.

INSERT INTO public.avatar_items (
    item_key, name, slot, equip_group, layer_order, asset_path,
    is_default, is_starter, is_tradeable, is_sellable, rarity, base_price, release_status,
    metadata, art_version, category, parts, dyes, hides, occupies, stack_order
)
VALUES
('angel_wings', 'Angel Wings', 'wings', 'wings', 0, '/avatar-px/items/angel_wings/icon.png?v=31974ebfe6', false, false, true, true, 'epic', 360, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'wings', '[{"slot":"wings","anchor":"body","x":3,"y":24,"w":26,"h":12,"frames":6,"src":"/avatar-px/items/angel_wings/0-wings.png?v=e7fecc5d43","fits":["body_kid","body_ghost"]}]'::jsonb, '{"dye1":"cloud"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('bat_swarm', 'Bat Swarm', 'aura', 'aura', 0, '/avatar-px/items/bat_swarm/icon.png?v=f1c44a1d27', false, false, true, true, 'legendary', 550, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"back_fx","anchor":"free","x":0,"y":13,"w":30,"h":34,"frames":6,"src":"/avatar-px/items/bat_swarm/0-back_fx.png?v=a66f594b30"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('bathing_suit', 'Bathing Suit', 'torso', 'torso', 0, '/avatar-px/items/bathing_suit/icon.png?v=4204bf3313', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/bathing_suit/0-torso.png?v=cbe9c08fd3","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry","dye2":"cloud"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('beach_towel', 'Beach Towel', 'neck', 'neck', 0, '/avatar-px/items/beach_towel/icon.png?v=2e3996bc9c', false, false, true, true, 'uncommon', 80, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'neck', '[{"slot":"neck","anchor":"body","x":12,"y":33,"w":7,"h":7,"frames":1,"src":"/avatar-px/items/beach_towel/0-neck.png?v=e1856feab3","fits":["body_kid"]}]'::jsonb, '{"dye1":"teal","dye2":"cloud"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('bobble_beanie', 'Bobble Beanie', 'head', 'head', 0, '/avatar-px/items/bobble_beanie/icon.png?v=5f9fc48636', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":11,"y":21,"w":10,"h":7,"frames":1,"src":"/avatar-px/items/bobble_beanie/0-head.png?v=1491d30017","fits":["body_kid"]}]'::jsonb, '{"dye1":"mustard","dye2":"cloud"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('body_pumpkin', 'Pumpkin', 'body', 'body', 0, '/avatar-px/items/body_pumpkin/icon.png?v=ca5bd1a689', false, false, true, true, 'rare', 300, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'body', '[{"slot":"body","anchor":"ground","x":8,"y":31,"w":16,"h":16,"frames":6,"src":"/avatar-px/items/body_pumpkin/0-body.png?v=d72dfae1f2"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('body_scarecrow', 'Scarecrow', 'body', 'body', 0, '/avatar-px/items/body_scarecrow/icon.png?v=cf7e77fdb9', false, false, true, true, 'epic', 450, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'body', '[{"slot":"body","anchor":"ground","x":4,"y":0,"w":24,"h":48,"frames":6,"src":"/avatar-px/items/body_scarecrow/0-body.png?v=adf3863eff"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('body_shadowbeast', 'Shadow Beast', 'body', 'body', 0, '/avatar-px/items/body_shadowbeast/icon.png?v=d6cc0114eb', false, false, true, true, 'legendary', 700, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'body', '[{"slot":"body","anchor":"ground","x":0,"y":15,"w":32,"h":32,"frames":6,"src":"/avatar-px/items/body_shadowbeast/0-body.png?v=c1df70f514"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('body_werewolf', 'Werewolf', 'body', 'body', 0, '/avatar-px/items/body_werewolf/icon.png?v=a296cfe508', false, false, true, true, 'legendary', 650, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'body', '[{"slot":"body","anchor":"ground","x":1,"y":21,"w":30,"h":26,"frames":7,"src":"/avatar-px/items/body_werewolf/0-body.png?v=00854f4365"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('cable_knit_sweater', 'Cable-Knit Sweater', 'torso', 'torso', 0, '/avatar-px/items/cable_knit_sweater/icon.png?v=360e3a8f28', false, false, true, true, 'uncommon', 140, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/cable_knit_sweater/0-torso.png?v=1e251fa503","fits":["body_kid"]}]'::jsonb, '{"dye1":"cloud"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('camp_tent', 'Camp Tent', 'companion', 'companion', 0, '/avatar-px/items/camp_tent/icon.png?v=962536d2c7', false, false, true, true, 'rare', 280, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":20,"y":39,"w":11,"h":8,"frames":6,"src":"/avatar-px/items/camp_tent/0-companion.png?v=db9b852967"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('candlestick', 'Candlestick', 'held', 'held', 0, '/avatar-px/items/candlestick/icon.png?v=c058625f0c', false, false, true, true, 'uncommon', 120, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":11,"y":32,"w":4,"h":7,"frames":5,"src":"/avatar-px/items/candlestick/0-held.png?v=4cdc729673","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('caramel_apple', 'Caramel Apple', 'held', 'held', 0, '/avatar-px/items/caramel_apple/icon.png?v=5a886df69d', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":11,"y":33,"w":5,"h":6,"frames":1,"src":"/avatar-px/items/caramel_apple/0-held.png?v=d54da01971","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('chunky_scarf', 'Chunky Scarf', 'neck', 'neck', 0, '/avatar-px/items/chunky_scarf/icon.png?v=c9c9f702b3', false, false, true, true, 'uncommon', 100, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'neck', '[{"slot":"neck","anchor":"body","x":11,"y":33,"w":9,"h":7,"frames":1,"src":"/avatar-px/items/chunky_scarf/0-neck.png?v=c1e16439a3","fits":["body_kid"]}]'::jsonb, '{"dye1":"pine"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('cowboy_hat', 'Cowboy Hat', 'head', 'head', 0, '/avatar-px/items/cowboy_hat/icon.png?v=2867d841b9', false, false, true, true, 'rare', 180, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":9,"y":20,"w":13,"h":6,"frames":1,"src":"/avatar-px/items/cowboy_hat/0-head.png?v=f8979ccdaa"}]'::jsonb, '{"dye1":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('flannel_shirt', 'Flannel Shirt', 'torso', 'torso', 0, '/avatar-px/items/flannel_shirt/icon.png?v=6214c2fbb2', false, false, true, true, 'uncommon', 120, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/flannel_shirt/0-torso.png?v=7bcfdc44e4","fits":["body_kid"]}]'::jsonb, '{"dye1":"cherry","dye2":"coal"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('ghost_pup', 'Ghost Pup', 'companion', 'companion', 0, '/avatar-px/items/ghost_pup/icon.png?v=61bac4eeec', false, false, true, true, 'epic', 340, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":20,"y":36,"w":10,"h":10,"frames":6,"src":"/avatar-px/items/ghost_pup/0-companion.png?v=053e34eba7"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hair_bald', 'Bald', 'hair', 'hair', 0, '/avatar-px/items/hair_bald/icon.png?v=05f2d42251', false, true, false, false, 'common', NULL, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'hair', '[{"slot":"hair","anchor":"head","x":15,"y":27,"w":1,"h":1,"frames":1,"src":"/avatar-px/items/hair_bald/0-hair.png?v=117dea6b94","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hair_bowl', 'Bowl Cut', 'hair', 'hair', 0, '/avatar-px/items/hair_bowl/icon.png?v=746e6ed862', false, true, false, false, 'common', NULL, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'hair', '[{"slot":"hair","anchor":"head","x":11,"y":23,"w":10,"h":7,"frames":1,"src":"/avatar-px/items/hair_bowl/0-hair.png?v=581680b093","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hair_buzz', 'Buzz Cut', 'hair', 'hair', 0, '/avatar-px/items/hair_buzz/icon.png?v=d3013e6b62', false, true, false, false, 'common', NULL, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'hair', '[{"slot":"hair","anchor":"head","x":11,"y":25,"w":9,"h":3,"frames":1,"src":"/avatar-px/items/hair_buzz/0-hair.png?v=aac3c81027","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hair_flat_top', 'Flat Top', 'hair', 'hair', 0, '/avatar-px/items/hair_flat_top/icon.png?v=4f6c709594', false, true, false, false, 'common', NULL, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'hair', '[{"slot":"hair","anchor":"head","x":12,"y":21,"w":8,"h":7,"frames":1,"src":"/avatar-px/items/hair_flat_top/0-hair.png?v=6692c9b99b","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hair_top_bun', 'Top Bun', 'hair', 'hair', 0, '/avatar-px/items/hair_top_bun/icon.png?v=16c34770e7', false, true, false, false, 'common', NULL, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'hair', '[{"slot":"hair","anchor":"head","x":11,"y":21,"w":10,"h":9,"frames":1,"src":"/avatar-px/items/hair_top_bun/0-hair.png?v=b000204a05","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('halo', 'Halo', 'head', 'head', 0, '/avatar-px/items/halo/icon.png?v=ef75109000', false, false, true, true, 'rare', 200, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":11,"y":19,"w":8,"h":4,"frames":1,"src":"/avatar-px/items/halo/0-head.png?v=a99e718cc4"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hot_cider', 'Hot Cider', 'held', 'held', 0, '/avatar-px/items/hot_cider/icon.png?v=47938dead3', false, false, true, true, 'common', 70, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":9,"y":34,"w":5,"h":6,"frames":5,"src":"/avatar-px/items/hot_cider/0-held.png?v=2ebf8b67be","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('jackalope', 'Jackalope', 'companion', 'companion', 0, '/avatar-px/items/jackalope/icon.png?v=cb3b708706', false, false, true, true, 'rare', 260, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":38,"w":8,"h":9,"frames":6,"src":"/avatar-px/items/jackalope/0-companion.png?v=e081f15a4d"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('leaf_crown', 'Leaf Crown', 'head', 'head', 0, '/avatar-px/items/leaf_crown/icon.png?v=a992eeddd6', false, false, true, true, 'uncommon', 100, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":10,"y":24,"w":11,"h":2,"frames":1,"src":"/avatar-px/items/leaf_crown/0-head.png?v=a08ee182a2","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('leaf_rake', 'Leaf Rake', 'held', 'held', 0, '/avatar-px/items/leaf_rake/icon.png?v=34c7084267', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":7,"y":19,"w":7,"h":27,"frames":1,"src":"/avatar-px/items/leaf_rake/0-held.png?v=777844cba0","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('little_bigfoot', 'Little Bigfoot', 'companion', 'companion', 0, '/avatar-px/items/little_bigfoot/icon.png?v=91224eb200', false, false, true, true, 'rare', 300, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":37,"w":7,"h":10,"frames":6,"src":"/avatar-px/items/little_bigfoot/0-companion.png?v=420afe0f68"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('mothman', 'Mothman', 'companion', 'companion', 0, '/avatar-px/items/mothman/icon.png?v=f9333854f1', false, false, true, true, 'epic', 380, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":13,"w":9,"h":7,"frames":6,"src":"/avatar-px/items/mothman/0-companion.png?v=ce84b6fe3a"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('pirate_eyepatch', 'Pirate Eyepatch', 'face_acc', 'face_acc', 0, '/avatar-px/items/pirate_eyepatch/icon.png?v=f57a2e1b94', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'face_acc', '[{"slot":"face_acc","anchor":"head","x":11,"y":28,"w":9,"h":4,"frames":1,"src":"/avatar-px/items/pirate_eyepatch/0-face_acc.png?v=b2d179071a","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('poncho', 'Poncho', 'outer', 'outer', 0, '/avatar-px/items/poncho/icon.png?v=475370540d', false, false, true, true, 'uncommon', 140, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'outer', '[{"slot":"outer","anchor":"body","x":10,"y":33,"w":11,"h":7,"frames":1,"src":"/avatar-px/items/poncho/0-outer.png?v=b5191eb182","fits":["body_kid"]}]'::jsonb, '{"dye1":"teal","dye2":"orange"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('puffer_vest', 'Puffer Vest', 'outer', 'outer', 0, '/avatar-px/items/puffer_vest/icon.png?v=b2e2076bcf', false, false, true, true, 'uncommon', 150, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'outer', '[{"slot":"outer","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/puffer_vest/0-outer.png?v=06edd4c047","fits":["body_kid"]}]'::jsonb, '{"dye1":"ocean"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('pumpkin_sweater', 'Pumpkin Sweater', 'torso', 'torso', 0, '/avatar-px/items/pumpkin_sweater/icon.png?v=9ef1e71cbd', false, false, true, true, 'uncommon', 130, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/pumpkin_sweater/0-torso.png?v=29b1cba0e1","fits":["body_kid"]}]'::jsonb, '{"dye1":"orange"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('raven', 'Raven', 'companion', 'companion', 0, '/avatar-px/items/raven/icon.png?v=5f1010b1e3', false, false, true, true, 'rare', 260, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":38,"w":9,"h":9,"frames":5,"src":"/avatar-px/items/raven/0-companion.png?v=1cd664a38d"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('rocket_pop', 'Rocket Pop', 'held', 'held', 0, '/avatar-px/items/rocket_pop/icon.png?v=7adad86792', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":12,"y":31,"w":3,"h":7,"frames":1,"src":"/avatar-px/items/rocket_pop/0-held.png?v=9c0172db03","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('soda_pop', 'Soda Pop', 'held', 'held', 0, '/avatar-px/items/soda_pop/icon.png?v=0f14eafe43', false, false, true, true, 'common', 50, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":11,"y":34,"w":3,"h":6,"frames":1,"src":"/avatar-px/items/soda_pop/0-held.png?v=555fc4f3df","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('swim_trunks', 'Swim Trunks', 'legs', 'legs', 0, '/avatar-px/items/swim_trunks/icon.png?v=c660e08d6d', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'legs', '[{"slot":"legs","anchor":"body","x":12,"y":39,"w":7,"h":2,"frames":1,"src":"/avatar-px/items/swim_trunks/0-legs.png?v=d31e476e24","fits":["body_kid"]},{"slot":"legs","anchor":"ground","x":13,"y":41,"w":5,"h":1,"frames":1,"src":"/avatar-px/items/swim_trunks/1-legs.png?v=f61f54481a","fits":["body_kid"]}]'::jsonb, '{"dye1":"ocean","dye2":"cloud"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('vampire_fangs', 'Vampire Fangs', 'face_paint', 'face_paint', 0, '/avatar-px/items/vampire_fangs/icon.png?v=1ce2cde7a8', false, false, true, true, 'common', 50, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'face_paint', '[{"slot":"face_paint","anchor":"head","x":15,"y":32,"w":3,"h":2,"frames":1,"src":"/avatar-px/items/vampire_fangs/0-face_paint.png?v=7910af49a6","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('witch_broom', 'Witch''s Broom', 'held', 'held', 0, '/avatar-px/items/witch_broom/icon.png?v=ea9ef89369', false, false, true, true, 'rare', 240, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":8,"y":21,"w":5,"h":25,"frames":1,"src":"/avatar-px/items/witch_broom/0-held.png?v=7eedf26d8f","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0)
ON CONFLICT (item_key) DO NOTHING;
