-- Shop items made from the arcade games' own sprites: Hemlock's Tower (its crow), Tlaloc's
-- Curse (the little warrior, the emerald and golden pinballs), Ooidash (the katana and the magnet) and
-- 8 Bit Evil Returns (the will-o'-wisp, the acid potion, the trophy and a heart), added if missing.
-- Rows from avatar_catalog.sql (made by npm run art:avatar). Run by the server at start; harmless to
-- run again.

INSERT INTO public.avatar_items (
    item_key, name, slot, equip_group, layer_order, asset_path,
    is_default, is_starter, is_tradeable, is_sellable, rarity, base_price, release_status,
    metadata, art_version, category, parts, dyes, hides, occupies, stack_order
)
VALUES
('acid_potion', 'Acid Potion', 'held', 'held', 0, '/avatar-px/items/acid_potion/icon.png?v=bea0b50a19', false, false, true, true, 'uncommon', 120, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":4,"y":30,"w":6,"h":8,"frames":6,"src":"/avatar-px/items/acid_potion/0-held.png?v=83fd58002e","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('emerald_pinball', 'Emerald Pinball', 'companion', 'companion', 0, '/avatar-px/items/emerald_pinball/icon.png?v=ee340e41d4', false, false, true, true, 'rare', 240, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":39,"w":8,"h":8,"frames":6,"src":"/avatar-px/items/emerald_pinball/0-companion.png?v=008b82b31a"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('extra_life', 'Extra Life', 'held', 'held', 0, '/avatar-px/items/extra_life/icon.png?v=6f495727b4', false, false, true, true, 'uncommon', 130, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":3,"y":31,"w":8,"h":7,"frames":1,"src":"/avatar-px/items/extra_life/0-held.png?v=d015765722","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('golden_pinball', 'Golden Pinball', 'companion', 'companion', 0, '/avatar-px/items/golden_pinball/icon.png?v=cca9c04b1c', false, false, true, true, 'epic', 340, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":39,"w":8,"h":8,"frames":6,"src":"/avatar-px/items/golden_pinball/0-companion.png?v=64055970e8"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hemlock_crow', 'Hemlock''s Crow', 'companion', 'companion', 0, '/avatar-px/items/hemlock_crow/icon.png?v=a9b7cc5d09', false, false, true, true, 'rare', 260, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":41,"w":7,"h":6,"frames":6,"src":"/avatar-px/items/hemlock_crow/0-companion.png?v=59807fb33d"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('katana', 'Katana', 'back', 'back', 0, '/avatar-px/items/katana/icon.png?v=81fc476fde', false, false, true, true, 'rare', 220, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'back', '[{"slot":"back","anchor":"body","x":8,"y":24,"w":16,"h":16,"frames":1,"src":"/avatar-px/items/katana/0-back.png?v=4f4f2cac60","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('magnet', 'Magnet', 'held', 'held', 0, '/avatar-px/items/magnet/icon.png?v=07138afcf9', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":4,"y":32,"w":6,"h":5,"frames":1,"src":"/avatar-px/items/magnet/0-held.png?v=56ec41e03c","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('tlaloc_warrior', 'Little Warrior', 'companion', 'companion', 0, '/avatar-px/items/tlaloc_warrior/icon.png?v=9aa88be1b7', false, false, true, true, 'epic', 380, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":21,"y":36,"w":8,"h":11,"frames":6,"src":"/avatar-px/items/tlaloc_warrior/0-companion.png?v=262fe3c945"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('trophy', 'Trophy', 'held', 'held', 0, '/avatar-px/items/trophy/icon.png?v=e3049a0f6d', false, false, true, true, 'legendary', 1000, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":3,"y":25,"w":8,"h":14,"frames":1,"src":"/avatar-px/items/trophy/0-held.png?v=8bfb3d6835","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('will_o_wisp', 'Will-o''-Wisp', 'companion', 'companion', 0, '/avatar-px/items/will_o_wisp/icon.png?v=05866a903a', false, false, true, true, 'epic', 360, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":20,"y":22,"w":12,"h":9,"frames":6,"src":"/avatar-px/items/will_o_wisp/0-companion.png?v=ce48aa8b3d"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0)
ON CONFLICT (item_key) DO NOTHING;
