-- Ten more shirts for the shop (a ringer tee, a band tee, a Hawaiian shirt, a baseball tee, tie-dye, a
-- tuxedo tee, a hi-vis vest, a turtleneck, a team jersey and a tank top), added if missing. Rows from
-- avatar_catalog.sql (made by npm run art:avatar). Run by the server at start; harmless to run again.

INSERT INTO public.avatar_items (
    item_key, name, slot, equip_group, layer_order, asset_path,
    is_default, is_starter, is_tradeable, is_sellable, rarity, base_price, release_status,
    metadata, art_version, category, parts, dyes, hides, occupies, stack_order
)
VALUES
('band_tee', 'Band Tee', 'torso', 'torso', 0, '/avatar-px/items/band_tee/icon.png?v=6605acde89', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/band_tee/0-torso.png?v=365eaf003d","fits":["body_kid"]}]'::jsonb, '{"dye1":"coal"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('baseball_tee', 'Baseball Tee', 'torso', 'torso', 0, '/avatar-px/items/baseball_tee/icon.png?v=fc306eea3e', false, false, true, true, 'common', 70, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/baseball_tee/0-torso.png?v=e6d4a874cf","fits":["body_kid"]}]'::jsonb, '{"dye1":"denim"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hawaiian_shirt', 'Hawaiian Shirt', 'torso', 'torso', 0, '/avatar-px/items/hawaiian_shirt/icon.png?v=44db67e351', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/hawaiian_shirt/0-torso.png?v=be5dec4a02","fits":["body_kid"]}]'::jsonb, '{"dye1":"teal","dye2":"mustard"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('hi_vis_vest', 'Hi-Vis Vest', 'torso', 'torso', 0, '/avatar-px/items/hi_vis_vest/icon.png?v=9e3fab19ee', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/hi_vis_vest/0-torso.png?v=804f7c56e4","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('ringer_tee', 'Ringer Tee', 'torso', 'torso', 0, '/avatar-px/items/ringer_tee/icon.png?v=893f64b4c2', false, false, true, true, 'common', 60, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/ringer_tee/0-torso.png?v=b1d3227f31","fits":["body_kid"]}]'::jsonb, '{"dye1":"cloud","dye2":"cherry"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('tank_top', 'Tank Top', 'torso', 'torso', 0, '/avatar-px/items/tank_top/icon.png?v=818a482b5a', false, false, true, true, 'common', 50, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/tank_top/0-torso.png?v=659b333289","fits":["body_kid"]}]'::jsonb, '{"dye1":"ash"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('team_jersey', 'Team Jersey', 'torso', 'torso', 0, '/avatar-px/items/team_jersey/icon.png?v=b1c823a48e', false, false, true, true, 'uncommon', 110, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/team_jersey/0-torso.png?v=fd614052e5","fits":["body_kid"]}]'::jsonb, '{"dye1":"ocean","dye2":"cloud"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('tie_dye_tee', 'Tie-Dye Tee', 'torso', 'torso', 0, '/avatar-px/items/tie_dye_tee/icon.png?v=bb8ba2bbcc', false, false, true, true, 'rare', 150, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/tie_dye_tee/0-torso.png?v=3dd42aedcc","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('turtleneck', 'Turtleneck', 'torso', 'torso', 0, '/avatar-px/items/turtleneck/icon.png?v=996bde4da4', false, false, true, true, 'uncommon', 100, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":33,"w":7,"h":6,"frames":1,"src":"/avatar-px/items/turtleneck/0-torso.png?v=f8e4d5c69f","fits":["body_kid"]}]'::jsonb, '{"dye1":"coal"}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('tuxedo_tee', 'Tuxedo Tee', 'torso', 'torso', 0, '/avatar-px/items/tuxedo_tee/icon.png?v=a51f260d93', false, false, true, true, 'uncommon', 100, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":5,"frames":1,"src":"/avatar-px/items/tuxedo_tee/0-torso.png?v=5312fe75ea","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0)
ON CONFLICT (item_key) DO NOTHING;
