-- Eight Halloween items for the shop: Frankenstein Bolts, Mummy Wraps, Grim Scythe, Spider Pal,
-- Black Cat, Reaper Hood, Stitches and Ghostly Aura. Their rows from avatar_catalog.sql (made by
-- npm run art:avatar), added if missing. Run by the server at start; harmless to run again.

INSERT INTO public.avatar_items (
    item_key, name, slot, equip_group, layer_order, asset_path,
    is_default, is_starter, is_tradeable, is_sellable, rarity, base_price, release_status,
    metadata, art_version, category, parts, dyes, hides, occupies, stack_order
)
VALUES
('black_cat', 'Black Cat', 'companion', 'companion', 0, '/avatar-px/items/black_cat/icon.png?v=e930cf8f0c', false, false, true, true, 'epic', 300, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":20,"y":37,"w":9,"h":10,"frames":6,"src":"/avatar-px/items/black_cat/0-companion.png?v=33b00d25e4"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('ghostly_aura', 'Ghostly Aura', 'aura', 'aura', 0, '/avatar-px/items/ghostly_aura/icon.png?v=bb09fb8fd3', false, false, true, true, 'legendary', 500, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'aura', '[{"slot":"back_fx","anchor":"free","x":0,"y":12,"w":23,"h":36,"frames":6,"src":"/avatar-px/items/ghostly_aura/0-back_fx.png?v=62ac8c66bb"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('grim_scythe', 'Grim Scythe', 'held', 'held', 0, '/avatar-px/items/grim_scythe/icon.png?v=bed37de162', false, false, true, true, 'epic', 380, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'held', '[{"slot":"held","anchor":"body","x":2,"y":19,"w":10,"h":27,"frames":1,"src":"/avatar-px/items/grim_scythe/0-held.png?v=f48c0fcd09","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('mummy_wraps', 'Mummy Wraps', 'torso', 'torso', 0, '/avatar-px/items/mummy_wraps/icon.png?v=dad5eac12d', false, false, true, true, 'rare', 180, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'torso', '[{"slot":"torso","anchor":"body","x":12,"y":34,"w":7,"h":6,"frames":1,"src":"/avatar-px/items/mummy_wraps/0-torso.png?v=4a3c795085","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('neck_bolts', 'Frankenstein Bolts', 'neck', 'neck', 0, '/avatar-px/items/neck_bolts/icon.png?v=0d4ebe541d', false, false, true, true, 'uncommon', 90, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'neck', '[{"slot":"neck","anchor":"body","x":11,"y":32,"w":9,"h":3,"frames":1,"src":"/avatar-px/items/neck_bolts/0-neck.png?v=1615ff9ad1","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('reaper_hood', 'Reaper Hood', 'head', 'head', 0, '/avatar-px/items/reaper_hood/icon.png?v=00e19189c9', false, false, true, true, 'epic', 320, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'head', '[{"slot":"head","anchor":"head","x":9,"y":22,"w":13,"h":13,"frames":1,"src":"/avatar-px/items/reaper_hood/0-head.png?v=f1235ad04d","fits":["body_kid"]}]'::jsonb, '{"dye1":"coal"}'::jsonb, ARRAY['hair']::text[], ARRAY[]::text[], 0),
('spider_pal', 'Spider Pal', 'companion', 'companion', 0, '/avatar-px/items/spider_pal/icon.png?v=20a76e5066', false, false, true, true, 'rare', 220, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'companion', '[{"slot":"companion","anchor":"free","x":24,"y":10,"w":7,"h":11,"frames":6,"src":"/avatar-px/items/spider_pal/0-companion.png?v=158e8e6e75"}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0),
('stitches', 'Stitches', 'face_paint', 'face_paint', 0, '/avatar-px/items/stitches/icon.png?v=9720a12b0a', false, false, true, true, 'common', 40, 'released', '{"source":"pixel-avatar"}'::jsonb, 3, 'face_paint', '[{"slot":"face_paint","anchor":"head","x":12,"y":28,"w":3,"h":5,"frames":1,"src":"/avatar-px/items/stitches/0-face_paint.png?v=c3f0d5e656","fits":["body_kid"]}]'::jsonb, '{}'::jsonb, ARRAY[]::text[], ARRAY[]::text[], 0)
ON CONFLICT (item_key) DO NOTHING;
