// Stable authored finds are shared by saves, co-op validation and both renderers.
// Item IDs never depend on a run, room code or random roll.
export const HIDDEN_PICKUPS = [
    { id: 'pickup-c1-road-rock', chapter: 1, area: 'overworld', scene: 'overworld', room: 0, x: 302, y: 558, name: 'Rock pocket snack', kind: 'snack', description: 'A wrapped cookie kept safe beneath a roadside rock. Restores 25 HP.', healHp: 25, walkover: true },
    { id: 'pickup-c1-diner', chapter: 1, area: 'overworld', scene: 'overworld', room: 0, x: 520, y: 405, name: 'Diner counter candy', kind: 'candy', description: 'A forgotten tin inside the diner, behind the counter. Six candy and 15 Ki.', candy: 6, healKi: 15, requiresDiner: true },
    { id: 'pickup-c1-vending', chapter: 1, area: 'overworld', scene: 'overworld', room: 0, x: 561, y: 440, name: 'Candy machine', kind: 'candy', description: 'The machine drops its last five candy and a little Ki. Its tray stays empty for this save.', candy: 5, healKi: 10 },
    { id: 'pickup-c1-wreck', chapter: 1, area: 'overworld', scene: 'overworld', room: 0, x: 400, y: 554, name: 'Lucky taxi bead', kind: 'trinket', description: 'The driver lost it when the boulder landed. +5% movement speed for the crew.', buff: 'speed', requiresWreck: true },
    { id: 'pickup-c1-road-crew', chapter: 1, area: 'overworld', scene: 'overworld', room: 0, x: 824, y: 552, name: '8 Bit Evil: the escape', kind: 'lore', description: 'Joe and Matt broke the old realm’s siege. Alex kept the exit open while Jon counted every head. Five quiet years later, the crew still checks that everybody made it home.' },
    { id: 'pickup-c1-tree-candy', chapter: 1, area: 'overworld', scene: 'overworld', room: 0, x: 760, y: 320, name: 'Tree hollow candy', kind: 'candy', description: 'Five candy hidden in a hollow trunk. Restores 15 Ki.', candy: 5, healKi: 15, walkover: true },
    { id: 'pickup-c1-station-card', chapter: 1, area: 'wayside', scene: 'hub', room: 0, x: 624, y: 128, name: 'Matt: measured sparks', kind: 'lore', description: 'Matt learned to save his strongest Ki for the moment it matters. He calls it patience. Joe calls it showing off with a timer.' },
    { id: 'pickup-c1-yard-snack', chapter: 1, area: 'wayside', scene: 'hub', room: 0, x: 640, y: 430, name: 'BBQ trail snack', kind: 'snack', description: 'One burger survived Joe’s grill. Restores 30 HP.', healHp: 30, walkover: true },
    { id: 'pickup-c1-west-charm', chapter: 1, area: 'wayside', scene: 'hub', room: 0, x: 300, y: 256, name: 'Wayside spark charm', kind: 'trinket', description: 'A small station charm, warm to the touch. Ki charges 10% faster.', buff: 'charge' },
    { id: 'pickup-c1-ash-cookie', chapter: 1, area: 'blast', scene: 'dungeon', room: 0, x: 144, y: 96, name: 'Ash-road cookie', kind: 'snack', description: 'A sealed lunchbox behind the scorched trees. Restores 25 HP.', healHp: 25, walkover: true },
    { id: 'pickup-c1-creek-card', chapter: 1, area: 'blast', scene: 'dungeon', room: 1, x: 208, y: 96, name: 'Monsters: hollow walkers', kind: 'lore', description: 'The walkers follow warmth, not noise. A charged Ki glow draws their empty eyes before they can hear a single footstep.' },
    { id: 'pickup-c1-yard-candy', chapter: 1, area: 'blast', scene: 'dungeon', room: 2, x: 384, y: 156, name: 'Ruined-yard candy', kind: 'candy', description: 'Six candy in an old glovebox. Restores 15 Ki.', candy: 6, healKi: 15, walkover: true },
    { id: 'pickup-c1-furnace-snack', chapter: 1, area: 'blast', scene: 'dungeon', room: 3, x: 560, y: 96, name: 'Furnace-pass snack', kind: 'snack', description: 'A traveler left this on the safe side of the furnace rocks. Restores 25 HP.', healHp: 25, walkover: true },
    { id: 'pickup-c1-sentinel-card', chapter: 1, area: 'blast', scene: 'dungeon', room: 4, x: 112, y: 96, name: 'Monsters: the Sentinel', kind: 'lore', description: 'The Sentinel waits where paths become gates. Its heavy rush is a warning as much as a weapon: something deeper in the crater needs a guard.' },
    { id: 'pickup-c1-courtyard-candy', chapter: 1, area: 'blast', scene: 'dungeon', room: 5, x: 624, y: 400, name: 'Courtyard Ki candy', kind: 'candy', description: 'A bright wrapper under fallen masonry. Five candy and 20 Ki.', candy: 5, healKi: 20, walkover: true },
    { id: 'pickup-c1-orchard-bead', chapter: 1, area: 'blast', scene: 'dungeon', room: 8, x: 240, y: 96, name: 'Orchard runner bead', kind: 'trinket', description: 'A scout’s bead tied with red string. +5% movement speed; does not stack with other runner trinkets.', buff: 'speed' },
    { id: 'pickup-c1-depot-card', chapter: 1, area: 'blast', scene: 'dungeon', room: 9, x: 384, y: 272, name: 'Jon: last one out', kind: 'lore', description: 'Jon says the rear guard gets the best view of a victory. His battered supply notes suggest he mostly gets the job of carrying everyone’s spare snacks.' },
    { id: 'pickup-c2-diner-card', chapter: 2, area: 'overworld', scene: 'overworld', room: 0, x: 608, y: 448, name: 'Alex: a light left on', kind: 'lore', description: 'Alex kept Wayside’s lamps burning during the old siege. Even a small light can tell a lost friend which way is home.' },
    { id: 'pickup-c2-road-snack', chapter: 2, area: 'overworld', scene: 'overworld', room: 0, x: 928, y: 448, name: 'Night-road biscuit', kind: 'snack', description: 'A fresh supply hidden along the east road. Restores 30 HP.', healHp: 30, walkover: true },
    { id: 'pickup-c2-pond-candy', chapter: 2, area: 'overworld', scene: 'overworld', room: 0, x: 480, y: 304, name: 'Pondside Ki candy', kind: 'candy', description: 'Six candy beneath a quiet willow. Restores 20 Ki.', candy: 6, healKi: 20, walkover: true },
    { id: 'pickup-c2-home-card', chapter: 2, area: 'wayside', scene: 'hub', room: 0, x: 864, y: 256, name: 'Joe: dinner with a power level', kind: 'lore', description: 'Joe’s cooking has survived two monster invasions and one angry grill. The crew still argues whether charging the barbecue with Ki improved the burgers.' },
    { id: 'pickup-c2-station-snack', chapter: 2, area: 'wayside', scene: 'hub', room: 0, x: 336, y: 176, name: 'Station platform snack', kind: 'snack', description: 'A station porter left supplies for the crew. Restores 30 HP.', healHp: 30, walkover: true },
    { id: 'pickup-c2-creek-candy', chapter: 2, area: 'blast', scene: 'dungeon', room: 1, x: 624, y: 416, name: 'Creek-bank candy', kind: 'candy', description: 'Five candy on a dry bank beyond the bridge. Restores 20 Ki.', candy: 5, healKi: 20, walkover: true },
    { id: 'pickup-c2-rift-charm', chapter: 2, area: 'blast', scene: 'dungeon', room: 6, x: 112, y: 288, name: 'Rift spark token', kind: 'trinket', description: 'A station token changed by the rift. Ki charges 10% faster; spark trinkets do not stack.', buff: 'charge' },
    { id: 'pickup-c2-watcher-card', chapter: 2, area: 'blast', scene: 'dungeon', room: 7, x: 496, y: 288, name: 'Monsters: the Watcher', kind: 'lore', description: 'The Watcher is a warning beacon for the Architect. When its dark nova flashes, every lesser monster knows that someone has reached the heart of the impact.' },
    { id: 'pickup-c2-realm-ghost', chapter: 2, area: 'eightbit-realm', scene: 'realm', room: 0, x: 96, y: 80, name: 'Monsters: lost echoes', kind: 'lore', description: 'Realm ghosts repeat the last thing they remember. Some still circle vanished doors. Others gather near the Architect’s Creation as though they recognize a voice inside.' },
    { id: 'pickup-c2-realm-cookie', chapter: 2, area: 'eightbit-realm', scene: 'realm', room: 0, x: 192, y: 304, name: 'Pixel pocket cookie', kind: 'snack', description: 'It looks square, but it tastes like home. Restores 30 HP.', healHp: 30, walkover: true },
    { id: 'pickup-c2-realm-candy', chapter: 2, area: 'eightbit-realm', scene: 'realm', room: 0, x: 304, y: 80, name: 'Flicker candy', kind: 'candy', description: 'Six candy bright enough to cut through the flicker. Restores 20 Ki.', candy: 6, healKi: 20, walkover: true },
    { id: 'pickup-c2-realm-runner', chapter: 2, area: 'eightbit-realm', scene: 'realm', room: 0, x: 432, y: 304, name: 'Eight-bit runner charm', kind: 'trinket', description: 'A little green boot with a very determined sparkle. +5% movement speed; runner trinkets do not stack.', buff: 'speed' },
    { id: 'pickup-c2-realm-pumpkin', chapter: 2, area: 'eightbit-realm', scene: 'realm', room: 0, x: 496, y: 80, name: 'Monsters: lantern heads', kind: 'lore', description: 'Pumpkin monsters use their inner flame to signal one another. Their glow grows sharper near a portal, even when the air is cold.' },
    { id: 'pickup-c2-realm-spark', chapter: 2, area: 'eightbit-realm', scene: 'realm', room: 0, x: 544, y: 288, name: 'Quiet spark prism', kind: 'trinket', description: 'A prism with one warm edge. Ki charges 10% faster; spark trinkets do not stack.', buff: 'charge' },
    { id: 'pickup-c2-realm-biscuit', chapter: 2, area: 'eightbit-realm', scene: 'realm', room: 0, x: 80, y: 288, name: 'Traveler’s biscuit', kind: 'snack', description: 'A biscuit left behind a broken realm column. Restores 25 HP.', healHp: 25, walkover: true },
    { id: 'pickup-c2-realm-architect', chapter: 2, area: 'eightbit-realm', scene: 'realm', room: 0, x: 368, y: 304, name: 'The Architect’s Creation', kind: 'lore', description: 'The egg breathes with the portal’s rhythm. The Architect called the old hordes a beginning. Nobody in Wayside likes what that makes the thing still sleeping inside.' },
];
const knownIds = new Set(HIDDEN_PICKUPS.map(item => item.id));
export function cleanFoundItems(value) {
    return [...new Set((Array.isArray(value) ? value : []).filter(id => knownIds.has(id)))];
}
